### ISSUE TITLE
Add CoinRemitter

### ISSUE THREAD

**Issue by design-app-web** [jdavis/twofactorauth#6136]
### Site name

CoinRemitter

### Site URL

https://coinremitter.com/

### Documentation URL

https://coinremitter.com/docs

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
@design-app-web the documentation link you provided doesn't describe how to enable 2FA on the service. Could you find another one that does?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by design-app-web** [comment]
![Screenshot 2021-10-04 at 11 01 10 AM](https://user-images.githubusercontent.com/85018348/135799235-fb6fb8b3-ac50-4d73-8cad-ed1a1ef9eccb.png)
