### ISSUE TITLE
Add Mos.ru

### ISSUE THREAD

**Issue by rakleed** [jdavis/twofactorauth#6158]
### Site name

Mos.ru

### Site URL

https://www.mos.ru/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/135743967-acd86df1-b0db-4701-83f7-6e69d7714fe7.png)

</details>

**Comment by Carlgo11** [comment]
@rakleed this site doesn't support 2FA via Electronic signatures?

**Comment by rakleed** [comment]
@Carlgo11 I could neither enable myself nor find information about the possibility of using an electronic signature as 2FA on this site.

**Comment by Carlgo11** [comment]
@rakleed I thought https://www.mos.ru/otvet-dokumenti/poluchit_elektronnuyu_podpis/#4 applied to mos.ru

**Comment by rakleed** [comment]
@Carlgo11 no, the link I provided earlier just describes well how an electronic signature works.
