### ISSUE TITLE
Add Госуслуги (Gosuslugi)

### ISSUE THREAD

**Issue by rakleed** [jdavis/twofactorauth#6159]
### Site name

Портал государственных и муниципальных услуг Российской Федерации (Госуслуги, Gosuslugi)

### Site URL

https://www.gosuslugi.ru/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [X] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/135744253-d9d6fb74-dbe6-4c71-80aa-d1f945eb2f2c.png)

</details>

**Comment by Carlgo11** [comment]
Privet @rakleed 👋 
What kind of hardware 2FA does the site support?

Also, is e-signature also some sort of 2FA method? If so, what kind?

**Comment by rakleed** [comment]
@Carlgo11 by hardware 2FA, I just meant an electronic signature, since as far as I understand, when receiving an electronic signature, a USB device is issued for its use.

More details: https://www.mos.ru/otvet-dokumenti/poluchit_elektronnuyu_podpis/#4
