### ISSUE TITLE
Website localization

### ISSUE THREAD

**Issue by Carlgo11** [jdavis/twofactorauth#6166]
Several people have asked for 2fa.directory in different languages over the years.
This is an issue to move all those issues into one.

* #3540
* #2510
* #3301
* #2531

Adding localization to the website UI may be possible with Jekyll and site variables (@kmpoppe [suggested](https://github.com/2factorauth/twofactorauth/issues/3540#issuecomment-458662463) a YAML file in #3540) or by using [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin) as proposed in #2531.

Technical suggestions are much appreciated!

**Comment by phallobst** [comment]
So for _N_ regions and _M_ languages, this means _NxM_ static pages using Jekyll? :raised_eyebrow:

**Comment by Carlgo11** [comment]
~195-210 regions and several thousand languages. No biggie :sweat_smile: 

JS would obviously be better. Hardcoding one language per region _could_ also be somewhat doable except for countries with multiple official languages.

**Comment by phallobst** [comment]
Switching languages via JavaScript would probably need to rearrange the category grid as well, since it should be sorted by category title (plus "Other" at the end). I don't see how this could play nice with Jekyll.
