### ISSUE TITLE
Enable region redirect through Cloudflare Workers

### ISSUE THREAD

**Issue by Carlgo11** [jdavis/twofactorauth#6221]
Since the merging of #6163 we now have the option to redirect users connecting to `https://2fa.directory/` to their regional version of our website if such a region is available.
This would benefit the users by only seeing the services that they can use, reducing clutter and load times. If we don't serve a site for the region of which the user connects from, they will be directed to the normal "global" site.

An example of this is available at [twofactorauth.net](https://twofactorauth.net/) (one of the domains we have).

I'd need some approvals before enabling this. Please vote and comment about any concerns/issues.

**Comment by phallobst** [comment]
One problem I see here is that users will be redirected whether they like it or not. If they _always_ want to see the "global" site, they would have to use "/int/" in their bookmarks - which isn't even the target page for the region dropdown.

**Comment by Carlgo11** [comment]
@phallobst That is indeed a limitation with the setup but I would argue very few people would want to see sites that are irrelevant to them.

Making the region dropdown use /int/ instead of the root directory could also be changed before enabling the redirect.

**Comment by sn00py1310** [comment]
To avoid any confusion there could be a notice.
`NOTICE: You're seeing a regional version. To see everything select global view.`

![Notice](https://user-images.githubusercontent.com/61204194/143682933-94a643a2-36b1-4c0b-b567-e3f0f8dc65ac.PNG)
Otherwise, I agree with @Carlgo11.

**Comment by ApCoder123** [comment]
@sn00py1310's comment reminds me that I had a similar idea a few weeks ago (forgot to upload this):

![2fa directory_gb_](https://user-images.githubusercontent.com/20560218/143685983-4e3799d9-4c30-47d7-90a1-9ad75e98f3c4.png)

**Comment by Carlgo11** [comment]
Taking @ApCoder123's example I made this on a dev branch that I'm working on.
Using `the {{country name}}` obviously only works for certain countries and specifying which countries would be annoying.
I instead opted for just using the country flag but I'm unsure about the `.` at the end of that sentence.
Would it look better on separate lines? Maybe the message should be rephrased so that it's only one sentence?

![light theme](https://user-images.githubusercontent.com/3535780/150024669-e90d5926-a887-48f6-9e4c-ba59fd123020.png)
![dark theme](https://user-images.githubusercontent.com/3535780/150024672-a1d8933b-a823-4431-9d5d-c37572f386cd.png)

**Comment by Carlgo11** [comment]
Here's the same message line separated:
![light theme](https://user-images.githubusercontent.com/3535780/150025762-d19481d7-4d12-436e-b057-37c3277ddaea.png)

I personally think that makes the message div too large.

**Comment by phallobst** [comment]
Maybe we could add an "X" to remove the message so that it will not be displayed all the time. We could use "localStorage" (instead of cookies) to remember whether to show that message.

**Comment by Carlgo11** [comment]
Like this?
![Screenshot 2022-01-21 at 00-23-14 2FA Directory](https://user-images.githubusercontent.com/3535780/150437919-57f1430e-8c9f-4e12-83f7-4f1c1c7d12e4.png)

**Comment by Carlgo11** [comment]
Here's a of it recording of it  in action.
I moved the cross closer and made the notice collapse rather than instantly disappear.

https://user-images.githubusercontent.com/3535780/150610704-bb445af3-abf8-4162-be4f-28fb7e145919.mp4
