### ISSUE TITLE
Update Co-Operative Bank

### ISSUE THREAD

**Issue by listerr** [jdavis/twofactorauth#6236]
### Site name

Co-Operative Bank

### Site URL

https://www.co-operativebank.co.uk/

### Update reason

It now supports 2FA.

### Additional information

Co-Operative Bank UK (For personal customers) have scrapped the use of their Chip+PIN hardware card challenge+response 
OTP readers, and instead implemented SMS based OTP with email as a backup if SMS is not available. A backward step IMHO.

https://www.co-operativebank.co.uk/digital-help/2fa/

https://www.co-operativebank.co.uk/content-hub/news-and-updates/how-we-recycle-your-old-card-readers/

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by phallobst** [comment]
From their documentation:
> When you're completing certain actions on your account, ...

Does this include logging in? Otherwise, this is _authorization_, but not _authentication_.
