### ISSUE TITLE
Add AnonAddy

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#6326]
### Site name

AnonAddy

### Site URL

https://anonaddy.com/

### Documentation URL

https://anonaddy.com/help/category/accounts-and-settings/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [X] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Add [AnonAddy] to Email

Documentation URL is WIP

**Comment by person1234-ux** [comment]
As much as i want to add this website it doesn't seem like it is eligible to be added because it is not ranked high enough
