### ISSUE TITLE
Add Kensington

### ISSUE THREAD

**Issue by elpory** [jdavis/twofactorauth#6338]
### Site name

DoungleAuth

### Site URL

https://www.dongleauth.com/dongles/

### Update reason

Other (please describe below).

### Additional information

Can Kensington [VeriMark portfolio](https://www.kensington.com/c/products/data-protection/biometric/?srt=newest) be added to the list of supported dongles. I have been using VeriMark Guard for my deployment without any issue and it works flawlessly. They offer [biometric security](https://www.kensington.com/solutions/product-category/why-biometrics/) for USB-A, USB-C and desktop solutions. Please refer to their page for more information 

They also have a support side with very detailed [step instructions ](https://www.kensington.com/software/verimark-setup/)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
We're not in any way affiliated with dongleauth.com. I recommend you contact them through their [github repo](https://github.com/nitrokey/dongleauth) instead.
