### ISSUE TITLE
Alexa.com closing down in May 2022 - change criteria to another service

### ISSUE THREAD

**Issue by mrjonstrong** [jdavis/twofactorauth#6339]
Just saw that Amazon are closing down the Alexa.com service used to validate if a site meets the criteria for addition.
[https://support.alexa.com/hc/en-us/articles/4410503838999](https://support.alexa.com/hc/en-us/articles/4410503838999
)
I think another service would need to be picked to replace it, perhaps something like [https://www.similarweb.com/](https://www.similarweb.com/)

**Comment by phallobst** [comment]
The [Cloudflare API](https://api.cloudflare.com/#domain-intelligence-get-domain-details) offers something similar. The response includes a "popularity_rank" - not sure how useful or accurate it is.

**Comment by phallobst** [comment]
I tried the free _DigitalRank API_ (5000 requests per month, results updated monthly) from similarweb.com:
```sh
> curl -s https://api.similarweb.com/v1/similar-rank/2fa.directory/rank?api_key=<KEY> | jq
{
  "meta": {
    "request": {
      "domain": "2fa.directory",
      "limit": 10,
      "format": "json"
    },
    "status": "Success",
    "last_updated": "2021-12-31"
  },
  "similar_rank": {
    "rank": 390299
  }
}
```
That should be sufficient for our purposes. With proper caching, we would never go near 5000 requests.

**Comment by phallobst** [comment]
Some further testing with the Similarweb API shows the following (as opposed to the Alexa API):

* `34SP.com` does not work ("Data not found"), but `34sp.com` does
* sub-domains like `accounts.firefox.com` or `hangouts.google.com` do not work at all

Nothing to lose sleep over, I guess.

**Comment by Carlgo11** [comment]
That might be preferable actually. That way things like forums wouldn't be boosted by their parent domains.
What's the price and limitations of their API?

**Comment by phallobst** [comment]
The Alexa API ignores sub-domains as well (so `handouts.google.com` would be ranked at 1, just like `google.com`), but does so without an error message.

The free Similarweb API access allows for 5000 requests per month (and apparently 10 per second). Anything above that is a bit pricey...
https://www.similarweb.com/corp/pricing/
https://www.similarweb.com/corp/learn-about-our-api/
https://support.similarweb.com/hc/en-us/articles/4414317910929
