### ISSUE TITLE
Performance issues on mobile 

### ISSUE THREAD

**Issue by FredHappyface** [jdavis/twofactorauth#6365]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

Thanks for this resource, looks like it'll be so useful in identifying accounts to enable 2fa on 🙂

### Information about the bug: ###
**Bug description:**

When accessing this site from a mobile device. The site performance is pretty poor. Searching for 'ebay' took a couple minutes. When entering the term, there was some pretty significant input lag 

**Bug reproduction:**

- Navigate to https://2fa.directory/
- Enter the term 'ebay' into the search field

**Impacted devices:**

Nokia 8 Sirocco, Android 10, Chrome 96

**Expected behavior:**

Performance should ideally see some improvement 

**Additional information:**

Thank you for your time

**Comment by Carlgo11** [comment]
The performance issue is a limitation to having a website only serving static content, as the javascript function needs to review all DOM entities and compare the data to the typed data.

The load time seems to be especially large on chromium based browsers. I can, for example, search near instantly when using Safari (WebKit).

One possible solution could be to send the search query through AJAX to a Cloudflare Worker and have it query the API file for content matches. That would however require funds to pay for the CF Worker requests. Funds which we do not have as this is a project with no income.

**Comment by stephenjust** [comment]
In this case, I wonder if a JavaScript framework like react or angular would be faster, since it works with a virtual DOM - or any solution where the data itself is held in memory as JSON and only the open sections are rendered to DOM instead of relying on CSS selectors and re-rendering the whole DOM on search string changes.

I've worked with much busier UIs than this with client side search that have performed much better, but have always relied on one of those two frameworks above. However it's definitely a big change from the way the site works today.

**Comment by FredHappyface** [comment]
Thanks for getting back to me on this

Looks like firefox (on android) has this issue too. Imo even adding some config to only search on a button press would improve this significantly on mobile 

Having used chrome tools to try and identify the bottleneck - it is almost certainly caused by manipulating the whole dom on every keypress 

Dev tools pointed me to the top link and the bottom may be useful 
- https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing
- https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution
