### ISSUE TITLE
Add a Ticketing / Events category

### ISSUE THREAD

**Issue by fletcherdodd** [jdavis/twofactorauth#6475]
- [X] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###
I think it would be beneficial to have a ticketing or events category for sites like Ticketmaster, Seatgeek, Eventbrite etc. Obviously, they could be classed as entertainment, however, I think that category covers online services/apps (Netflix, Apple Music, Etc.). There are plenty of these types of sites internationally so I don't think it would go unused.

**Comment by phallobst** [comment]
We currently only have one entry, if I'm not mistaken (_EVENTIM_), which is in the `retail` category. I reckon we should get at least five before we open up a new category.

**Comment by fletcherdodd** [comment]
Eventbrite is sitting in social and I have those 3 PRs. I have a couple more to add that would fit it with it. Maybe after I request them?
