### ISSUE TITLE
Add Whalefin

### ISSUE THREAD

**Issue by CCharlieLi** [jdavis/twofactorauth#6498]
### Site name

Whalefin

### Site URL

https://www.whalefin.com/

### Documentation URL

https://support.whalefin.com/hc/en-us/articles/4403359735961-How-to-enable-Google-Authenticator-2FA-on-WhaleFin-App-

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

The Alexa rank is now  24,120, probably because of the rebranding, still think it's worthy to be added in 2fa.directory, also recomanded by our clients.

**Comment by CCharlieLi** [comment]
#6497

**Comment by phallobst** [comment]
Opening a PR is totally sufficient, there is no need for a corresponding issue. I have linked them now.
