### ISSUE TITLE
Add Sony Bank

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#6510]
### Site name

Sony Bank

### Site URL

https://moneykit.net/en/

### Documentation URL

https://moneykit.net/visitor/otp/ataglance/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [X] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by ghost** [comment]
- Keywords: banking
- Regions: JP

**Comment by ghost** [comment]
Sony Bank provides two factor authorization, but not two factor authentication. close

**Comment by phallobst** [comment]
We could still list Sony Bank as _not_ supporting 2FA.

**Comment by ghost** [comment]
> We could still list Sony Bank as _not_ supporting 2FA.

I will submit a pull request at a later date after I have carefully checked to see if it really does not support 2FA.

**Comment by ghost** [comment]
Research complete, PR to be submitted.
