### ISSUE TITLE
Add Amazon.co.jp

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#6511]
### Site name

Amazon.co.jp

### Site URL

https://www.amazon.co.jp/

### Documentation URL

https://www.amazon.co.jp/gp/help/customer/display.html?nodeId=G3PWZPU52FKN7PW4

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [X] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

An Amazon.co.jp account is independent of an Amazon.com account.

**Comment by ghost** [comment]
- Keywords: Backup and Sync(Amazon Cloud Drive), Paymants([Amazon Pay JP](https://pay.amazon.co.jp/)), Retail, 
- Regions: Global

**Comment by phallobst** [comment]
`amazon.co.jp` is already one of the _additional domains_ of the `amazon.com` entry. Even if the account is independent - are the 2FA options different? Does it merit an entry of its own?

**Comment by ghost** [comment]
@phallobst 
The 2FA option is the same.
