### ISSUE TITLE
Add National Diet Library Online(Japan)

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#6512]
### Site name

National Diet Library Online

### Site URL

https://ndlonline.ndl.go.jp/#!/

### Facebook

https://www.facebook.com/NDLexhibition

### Twitter

@NDLJP

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

- Keywords: Education, Government
- Regions: JP

**Comment by phallobst** [comment]
I'm not sure how this website meets our [Site Criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria). Could you elaborate on that?

**Comment by ghost** [comment]
@phallobst This web service contains a record of reading. It is important for privacy reasons.

**Comment by Carlgo11** [comment]
Search records aren't by themselves PII. Closing as the service doesn't meet the site criteria.
