### ISSUE TITLE
Add Starbucks(Japan)

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#6514]
### Site name

Starbucks

### Site URL

https://www.starbucks.co.jp/

### Facebook

https://www.facebook.com/StarbucksJapan

### Twitter

@Starbucks_J

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

- Alexa: 15,305
----
- Keywords: Food
- Regions: JP

**Comment by phallobst** [comment]
We already list Starbucks. Does the SMS 2FA option (https://customerservice.starbucks.com/app/answers/detail/a_id/6180) not apply in Japan?

**Comment by ghost** [comment]
@phallobst
Starbucks in Japan is a unique account, independent from the rest of the world.
Both your email address and password are independent.
