### ISSUE TITLE
Add gamersgate.com

### ISSUE THREAD

**Issue by 32423d** [jdavis/twofactorauth#6552]
### Site name

GAMERSGATE

### Site URL

https://www.gamersgate.com/

### Facebook

https://www.facebook.com/GamersGate

### Twitter

https://twitter.com/GamersGate

### Email address

help@gamersgate.com

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

This site is an online retailer for video game keys. The keys are obtained directly from the game publishers. Even though this site does not rank within the 200,000 sites on Alexa it does have a substantial social media following (retailer is verified on twitter).

**Comment by Carlgo11** [comment]
@32423d since you've checked the box saying you've searched for duplicate pull requests I assume you know GamersGate is already listed, so what else do you want?

**Comment by 32423d** [comment]
My apologies. I got the issue tracker mixed up with the pull request tracker so I accidentally listed it as a site that hasn't been added before.

**Comment by Carlgo11** [comment]
It's still not clear what you're actually trying to do here. Did you want to change something with the entry?
