### ISSUE TITLE
Add Vagaro

### ISSUE THREAD

**Issue by 40504** [jdavis/twofactorauth#6645]
### Site name

Vagaro

### Site URL

https://www.vagaro.com

### Documentation URL

https://support.vagaro.com/hc/en-us/articles/115005413687

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

![vagaro com](https://user-images.githubusercontent.com/71176569/162568007-ecf39ad9-923f-4739-b7d5-5c9b43d14ca5.svg)

**Comment by phallobst** [comment]
The doc page says "Business and Employee Settings" - does this not apply to regular users of this site then?

**Comment by 40504** [comment]
I have no idea, I don't an account for "Vagaro"
