### ISSUE TITLE
Add SimpleLogin SAS

### ISSUE THREAD

**Issue by c0nfigurati0n** [jdavis/twofactorauth#6658]
### Site name

SimpleLogin SAS

### Site URL

simplelogin.io

### Documentation URL

No public documentation. Find instructions attached.

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [X] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [ ] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

![homepage](https://user-images.githubusercontent.com/81120877/163313120-9dc4717c-6b4e-43cf-a8ec-36e31a15509b.png)
![dashboard1](https://user-images.githubusercontent.com/81120877/163313106-a7d9056b-54b3-423e-8f26-226e0e49d9dc.png)
![dashboard2](https://user-images.githubusercontent.com/81120877/163313115-b62a8d98-8c1c-4481-a07a-5a5010bfbe7d.png)
![login](https://user-images.githubusercontent.com/81120877/163313141-b80b43e3-1894-44ab-acaa-429d1a8f8c77.png)
![recovery1](https://user-images.githubusercontent.com/81120877/163313154-10f46650-8425-49f4-9dd8-099f59ba36e7.png)
![recovery2-notext](https://user-images.githubusercontent.com/81120877/163313168-41ff2eff-47fb-41f3-9ae4-33221037212b.png)
![recovery2-text](https://user-images.githubusercontent.com/81120877/163313176-5a37a321-e188-4343-9a6d-e6cab3021840.png)
![recovery3](https://user-images.githubusercontent.com/81120877/163313189-4c6881ba-9576-4a3f-a1e0-12da60f752c0.png)
![securitykey](https://user-images.githubusercontent.com/81120877/163313201-9138a968-59ef-4942-9266-17f12d4a8e57.png)

**If i did not redact something very well, please contact me at the email address on my profile.**

**Comment by noahggarrett-1** [comment]
I agree this should be added

**Comment by person1234-ux** [comment]
https://github.com/2factorauth/twofactorauth/pull/6699

**Comment by person1234-ux** [comment]
I added https://github.com/2factorauth/twofactorauth/pull/6715 long story should my other respotory got corrupted when using githubs gui thanks github

**Comment by c0nfigurati0n** [comment]
@phallobst @person1234-ux i am confused. Does this mean you all are going to add SimpleLogin?

**Comment by person1234-ux** [comment]
@therealmrmuffin they should added we just need for them to review my pull request

**Comment by noahggarrett-1** [comment]
Ok

**Comment by c0nfigurati0n** [comment]
@nguyenkims mind taking a look?

**Comment by nguyenkims** [comment]
@therealmrmuffin thanks for adding SimpleLogin to this repository!

**Comment by therealmrmuffin** [comment]
> @therealmrmuffin thanks for adding SimpleLogin to this repository!

Don't thank me!

Thank the 2fa.director team! :D
