### ISSUE TITLE
Update HMRC

### ISSUE THREAD

**Issue by gazelle-24** [jdavis/twofactorauth#6667]
### Site name

HMRC

### Site URL

https://hmrc.gov.uk/

### Update reason

Its documentation link has changed., The methods of 2FA that it supports have changed.

### Additional information

* Please add Software Token (screenshots below).
* Current documentation link does not direct to instructions for setting up 2FA, please change to https://www.gov.uk/government/publications/access-our-services-using-government-gateway/advice-for-super-users#how-to-set-up-multi-factor-authentication (unfortunately I can only find instructions for Super Users and not regular users of HMRC site).
![Screenshot 2022-04-15 at 21 46 26](https://user-images.githubusercontent.com/40043643/163690970-22d6d5aa-e266-4051-8157-4dc7e57cc0f1.png)
![Screenshot 2022-04-15 at 21 51 12](https://user-images.githubusercontent.com/40043643/163690972-bf9719fe-fd68-473c-8d66-54f5327f7927.png)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
@gazelle-24 Do all subdomains of gov.uk use the same authentication system?

**Comment by gazelle-24** [comment]
@Carlgo11 No, for example test-for-coronavirus.service.gov.uk/report-result/ uses NHS login and account.student-finance.service.gov.uk uses Student Finance England login (logon.slc.co.uk).
