### ISSUE TITLE
Unsure if site qualifies to be added

### ISSUE THREAD

**Issue by aarontorres0** [jdavis/twofactorauth#6670]
I was looking into submitting a pr for standardnotes.com, but after reading the Site Criteria I am not too sure if it qualifies to be added. I think it qualifies under the second criteria, Data. Can I get another opinion on this.

**Comment by phallobst** [comment]
Since they offer paid plans/subscriptions and presumably need the billing information on record, the _money_ part applies as well.

**Comment by aarontorres0** [comment]
Yes, that is also true. I will go ahead and submit a pr. Also, do you think this should go under Backups or Other

**Comment by phallobst** [comment]
There are three similar entries:
* Evernote (`backup`)
* Notejoy (`communication`)
* Nimbus Note (`task`)

You should pick one of them - ideally, they'd be all in the same category.
