### ISSUE TITLE
Public key question

### ISSUE THREAD

**Issue by tendervittles** [jdavis/twofactorauth#6690]
Hello,

Where can I find your public key for `*.sig` verification?

I searched for the key ID used for signing, but couldn't find anything.

It would be nice if this info was on your main your README, or at least on the api.md page.

Thanks!

**Comment by Carlgo11** [comment]
Hello @tendervittles,
you can either download the public key via:
```
dig +short 2fa.directory CERT
```
or import it directly to your GPG keyring with:
```
echo "" | gpg --encrypt --armor --auto-key-locate cert -r security@2fa.directory
```

**Comment by tendervittles** [comment]
Thanks @Carlgo11
