### ISSUE TITLE
Update College Board

### ISSUE THREAD

**Issue by hkamran80** [jdavis/twofactorauth#6692]
### Site name

College Board

### Site URL

https://www.collegeboard.org/

### Update reason

It now supports email 2FA.

### Additional information

College Board now supports email 2FA, as part of their new authentication system.

<img width="549" alt="collegeboard_mfa" src="https://user-images.githubusercontent.com/16967687/166507161-15d8814a-34d4-4d11-961f-4d9b8852f541.png">

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by phallobst** [comment]
FYI: You don't need to open an issue if you are planning to create a PR anyway.

**Comment by hkamran80** [comment]
Ah, good to know. Thanks!
