### ISSUE TITLE
Remove [Free Dns]

### ISSUE THREAD

**Issue by person1234-ux** [jdavis/twofactorauth#6719]
### Site name

Free Dns

### Site URL

https://freedns.afraid.org/

### Removal reason

It no longer has verifiable 2FA documentation and is no longer ranked within the top 200,000 sites on Similarweb.

### Additional information

This website doesn't have 2fa and id doesn't it doesn't have the required rating. It also looks like a old 1990 website.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by phallobst** [comment]
Similarweb does not provide ranks for subdomains. [afraid.org](https://afraid.org) is at 162,304 right now, so still within the 200k range.

**Comment by person1234-ux** [comment]
we should remove them there ssl is doesn't even work @phallobst
