### ISSUE TITLE
Update Kraken

### ISSUE THREAD

**Issue by Sami32** [jdavis/twofactorauth#6730]
### Site name

Kraken

### Site URL

Https://www.kraken.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Email

https://support.kraken.com/hc/en-us/articles/360060822772-Approving-a-new-device

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by phallobst** [comment]
Is the approval process related to 2FA logins? Maybe it's just a bit of additional security when you do _not_ use 2FA.

**Comment by Sami32** [comment]
@phallobst Yes.
You CANNOT login into your Kraken account without entering the code received in your email when using a new device.
So in such cases it become like a kind of 3FA login (edited).

"After you have started the sign in process by entering your username, password and sign-in 2FA, our system will detect whether a new device is being used to access your account.

If you are signing in on a new device, our system will send out an email to the email address that is associated with your Kraken account. We do this in order to verify that it is you, the account owner, that is trying to sign in."

**Comment by Carlgo11** [comment]
>You CANNOT login into your Kraken account without entering the code received in your email when using a new device.
So in such cases it become 3FA logins.

It wouldn't be three factors as email is a [possession factor](https://en.wikipedia.org/wiki/Multi-factor_authentication#Factors) just like all the other 2FA methods supported by Kraken.

I'll create a PR to update the entry.

**Comment by person1234-ux** [comment]
@Carlgo11 I would just add this as a note for the entry

**Comment by phallobst** [comment]
Is `email` a valid 2FA method that can be use on its own? It doesn't seem to be the case, if I'm understanding this correctly. The user might be asked to confirm the new device by a code sent via email, but still needs the regular second factor.

**Comment by Sami32** [comment]
@phallobst Correct, you still needs the regular second factor.
`Email` cannot be used on its own, neither OTP.

Its an additional and mandatory mean to provide a way to verify "Something the user is": his browser fingerprint , Something the user has: an email and Something the user knows: a code.

Note that it not optional like some 2FA method already added to the listing (TOTP with Nuri).
