### ISSUE TITLE
Add genome.dantelabs.com

### ISSUE THREAD

**Issue by Loqova** [jdavis/twofactorauth#6756]
### Site name

Genome Manager Dante Labs

### Site URL

https://genome.dantelabs.com/

### Facebook

https://www.facebook.com/DanteLabs/

### Twitter

https://twitter.com/dantelabs

### Email address

contact@dantelabs.com

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

GDPR requires sufficient protection of "personal data". Danta Labs does whole genome sequencing, meaning the literally have the full DNA profile of a lot of people. It doesn't get any more "personal" than that. Yet their Genome Manager Portal is only protected by a username and password. No two factor authentication (TFA) whatsoever.

**Comment by person1234-ux** [comment]
this issue has been in correctly filled out the website doesn't meet the ranking requirement

**Comment by Carlgo11** [comment]
Nice catch @person1234-ux! :clap:

Closing the issue.

**Comment by person1234-ux** [comment]
Thanks it was an easy catch
