### ISSUE TITLE
Update [Piwik]

### ISSUE THREAD

**Issue by Draky50110** [jdavis/twofactorauth#6764]
### Site name

Matomo

### Site URL

https://matomo.org/

### Update reason

Its name has changed.

### Additional information

Name changed from Piwik to Matomo in january 2018.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Draky50110** [comment]
Ok, in fact Piwik is listed under "Developer" and Matomo is listed under "Marketing".

Piwik does no longer exists as it has been renamed.

There a are 2 products :
- cloud hosted matomo instance
- self hosted matomo instance

Both have 2FA.

**Comment by phallobst** [comment]
The "Piwik" entry is actually "Piwik PRO", which is a separate entity from "Matomo", if I understand that correctly. Maybe it would be easier and less confusing to rename it to "Piwik PRO".

Apart from that, it should probably get the (single or additional) `marketing` keyword.
