### ISSUE TITLE
Viewing Issue on Mobile Browsing

### ISSUE THREAD

**Issue by fletcherdodd** [jdavis/twofactorauth#6809]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**
Viewing the different categories is not possible on mobile browsers

**Bug reproduction:**
After loading the website (2FA.directory) when you tap on a category to expand it and view the sites listed in it it highlights the box but doesn't display any websites.

**Impacted devices:**
Appears to be on both iOS and Android (both devices running the latest versions). Tried different browsers, Safari, Chrome, Edge and Brave all had the same result

**Expected behavior:**
After tapping on a category it would explain and display related websites

**Additional information:**
Tried clearing browsing data and also using private mode which had no effect. Also can confirm they aren't opening anywhere else on the page (e.g bottom of the page)

https://user-images.githubusercontent.com/7688583/174801339-511dc85d-876f-4040-96fc-49ee408cad20.MOV

**Comment by Carlgo11** [comment]
Seems to work now on some devices. More devices will receive the fix as the cache gets refreshed by more edge nodes.

https://user-images.githubusercontent.com/3535780/174863243-5d067de8-61ba-4ba9-8196-79da8a95a2a5.MOV
