### ISSUE TITLE
Add disroot.org

### ISSUE THREAD

**Issue by Sami32** [jdavis/twofactorauth#6818]
### Site name

Disroot

### Site URL

Https://www.disroot.org

### Documentation URL

https://howto.disroot.org/en/tutorials/cloud/settings#two-factor-authentication

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [X] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Email

**Comment by Carlgo11** [comment]
Seems similar to #6820 in that it's a bundle of open source [self-hosted software](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#self-hosted-services) along with a [forum](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#forums).

**Comment by Sami32** [comment]
>*8. Using Disroot services for commercial activities*

*Disroot* is a non-profit organization providing services for individuals on "pay as you wish" basis. Because of this structure we see using *Disroot* services for commercial purposes as an abuse of the service and it will be treated as such.


If NGO or associations are excluded then yes.

I apology for my bad understanding of your criteria.


----------------------------------------

24 juin 2022 22:11:27 Carlgo11 ***@***.***>:

**Comment by Carlgo11** [comment]
I'm sure it's a great service and the idea is honorable but it doesn't fit the criteria for services which we list.
Sorry for the inconvenience.
