### ISSUE TITLE
Add Murena.io

### ISSUE THREAD

**Issue by Sami32** [jdavis/twofactorauth#6819]
### Site name

Murena

### Site URL

Https://murena.io

### Documentation URL

https://doc.e.foundation/support-topics/two-factor-authentication

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Has been recently rebranded to Murena (before it was ecloud.email from the e.foundation).
https://www.similarweb.com/website/e.foundation/#overview

**Comment by Carlgo11** [comment]
Is it just a NextCloud instance?

**Comment by Sami32** [comment]
Not only:
https://e.foundation/ecloud/

But as users we don't have to install anything to have access to their services.

----------------------------------------

24 juin 2022 22:13:41 Carlgo11 ***@***.***>:

**Comment by person1234-ux** [comment]
This website isn't eligible as it doesn't meet the site rank requirement
