### ISSUE TITLE
Add snopyta.org

### ISSUE THREAD

**Issue by Sami32** [jdavis/twofactorauth#6820]
### Site name

Snopyta

### Site URL

https://snopyta.org/

### Email address

support@snopyta.org

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Based in Sweden.

**Comment by Carlgo11** [comment]
Looks to just be a bunch of [self hosted services](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#self-hosted-services) which we don't list.

**Comment by Sami32** [comment]
https://docs.invidious.io/instances/

https://account.snopyta.org/pwm/

Feel free to close it if it meet your exceptions criteria but we don't have to host anything to use their email service.
My english is probably too weak.

Regards,

----------------------------------------

24 juin 2022 22:03:42 Carlgo11 ***@***.***>:
