### ISSUE TITLE
Moring forward with my advance works and a back up with my future works 

### ISSUE THREAD

**Issue by Benson665** [jdavis/twofactorauth#6840]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

**Comment by Benson665** [comment]
Ok thanks still moving forward for my search

**Comment by Benson665** [comment]
Not even a comment on my birthday last weekend well I don't mind keep moving No stopping

**Comment by Carlgo11** [comment]
@Benson665 I don't know what you're trying to do but this isn't the right place for it. If you continue to make issues here that are unrelated to the project, you will be banned.

**Comment by Benson665** [comment]
Sorry for disturbing you

**Comment by Benson665** [comment]
I received a email to search for something that
was sent to my account to get it out, need to get it  to finance all my system needs, if not I will turn a deaf ear to all the bills I need to do in the system and sorry if I'm disturbing you with my problem
