### ISSUE TITLE
Add TeslaFi

### ISSUE THREAD

**Issue by kennedy** [jdavis/twofactorauth#6859]
### Site name

TeslaFi

### Site URL

https://teslafi.com

### Documentation URL

https://teslafi.com/twofactor.php

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by phallobst** [comment]
The page https://teslafi.com/twofactor.php is only accessible after login. Could you provide a screenshot of the setup page with your personal information redacted?

**Comment by kennedy** [comment]
The link did not provide much information, but a URL to a general explaination of 2fa https://medium.com/binaryboot/how-to-setup-2-factor-authentication-with-totp-authenticator-complete-2fa-guide-513e2ea904f3

but here is a screenshot
![Screenshot 2022-07-18 at 23-42-49 Two Factor Authentication Setup](https://user-images.githubusercontent.com/854543/179635212-905d01aa-2ea5-4dc9-a2b2-ce0a35c207d0.png)
