### ISSUE TITLE
Add Revolut

### ISSUE THREAD

**Issue by Nathanymous** [jdavis/twofactorauth#6890]
### Site name

Revolut

### Site URL

https://www.revolut.com

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [x] SMS tokens
- [x] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Revolut is a banking service for credit cards. It is based in all countries of the EU, and in Australia, Singapore, Switzerland, Japan, the United Kingdom and the United States.
The SMS verification is an extra layer of security for certain things as payments and seeing personal (privacy sensitive) info.
The SMS verification is mandatory to set up.

There is no documentation available for setting up the SMS verification, and i can't make screenshots either, as it is setup on account creation. (You can only make 1 account to avoid scammers).

**Comment by phallobst** [comment]
According to https://www.revolut.com/en-US/help/more/revolut-web-app/accessing-the-retail-web-app, they offer `sms`, `email` and `custom-software` (push notification in their app). Can you confirm that @NathanVerkerk?

**Comment by Nathanymous** [comment]
I can confirm all. I am sorry for not seeing this right away.
There are a few notes:
All of these can be used for logging in the web app. If you log in with `custom software`, only then you will have full access to the web app features, because of safety.
The `sms` and `email` codes only provide limited functionality in the web app when used to log in.
