### ISSUE TITLE
export list of sites to csv

### ISSUE THREAD

**Issue by sqenixs** [jdavis/twofactorauth#6898]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

It would be really useful to have a button to export the list to csv.

**Comment by phallobst** [comment]
You can download the data as a JSON file, e.g. https://2fa.directory/api/v3/all.json (see [api.md](https://github.com/2factorauth/twofactorauth/blob/master/api.md) for more information). That list can be converted to CSV or any other format you like. There is an online tool at https://www.convertcsv.com/json-to-csv.htm for example. However, since there are some 1:N relations in the data, a CSV file might become a bit messy.

**Comment by sqenixs** [comment]
Yes it is messy.  What I meant was some way to filter the data so for example say you want a list of all domains accessible from USA that support authenticator apps.  That would give you a list.  This would aid people that want to compare against output from a password manager, to know what sites they use that support 2fa.  In other words, a way to manually compare the site data against password manager data to find opportunities to strengthen security, that doesn't require reorganizing the data manually for people that are not tech-savvy.

**Comment by Carlgo11** [comment]
What you're looking for it a list of all our entries, [all.json](https://2fa.directory/api/v3/all.json), processed to output only data relevant to your specific need.
We offer the data but can't possibly offer it processed to every persons needs for free. You'll need to write code for that.
If you're tech-savvy enough for a CSV file I recommend you follow the steps @phallobst outlined and process the data in Excel or what ever program you're using.

Several password managers also integrate directly with our API. If your password manager of choice doesn't support that, make a feature request to the developers of that password manager.
