### ISSUE TITLE
Add 2game.com

### ISSUE THREAD

**Issue by 32423d** [jdavis/twofactorauth#6899]
### Site name

2GAME

### Site URL

2game.com

### Facebook

https://www.facebook.com/2gameofficial

### Twitter

https://twitter.com/2game

### Email address

support@2game.com

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

2GAME is a online retailer that sells game keys that can be used to activate games. The keys are obtained directly from the publishers of the game keys that they sell. The site isn't ranked within the 200,000 sites on Similarweb but it does have a substantial social media following and the website is for a legitimate business.

**Comment by Carlgo11** [comment]
As it doesn't meet the SimilarWeb criteria there would be a significant social media following to offset the lack of the website popularity. This is designed for things like popular phone apps that lack a website version.
2Game.com's social media following of 22K followers on Twitter and 18K on Facebook isn't significant enough for us to disregard the SimilarWeb rank.
Feel free to reopen this issue if the website rank changes.
