### ISSUE TITLE
Add support for listing enforcement/reporting features of the vendor if applicable

### ISSUE THREAD

**Issue by kurtseifried** [jdavis/twofactorauth#6902]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

So a lot of vendors support 2FA which is good. But for the organization/corporate side of things (e.g. where an account belongs not to an individual, but to an employee/contractor/etc of an organization) and 2FA needs to be enforced it would be nice to know if the vendor:

1) Supports enforcement of using 2FA/MFA Y/N
2) Supports enforcement of what kind(s) of 2FA/MFA a user can pick (e.g. disable SMS, only allow hardware tokens or FIDO)
3) Supports generating reports on compliance (especially if #2 is a no) so that administrators can ensure users are using approved methods (even if it can't be technically enforced).

Some examples of this are Microsoft365, you can enforce 2FA/MFA, but you can't restrict which types, or Google WorkSuite where you can enforce it, and restrict which types of 2FA are allowed (selectively at the organizational unit even).

**Comment by Carlgo11** [comment]
Hello Kurt,
the aim of 2fa.directory is to aid consumers in choosing secure online services. I can see how your proposed features could be good for corporate users such as CISOs and compliance officers but I'm afraid that's out of scope of this project.

The corporate world might be something we branch out to in the future, possibly as a paid version, but at the moment we have no such plans.
