### ISSUE TITLE
Add  FitnessSyncer.com

### ISSUE THREAD

**Issue by stacksjb** [jdavis/twofactorauth#6920]
### Site name

FitnessSyncer

### Site URL

https://www.fitnesssyncer.com/

### Documentation URL

https://www.fitnesssyncer.com/support/two-factor-authentication

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Category: Health

Supports Software-based token only

**Comment by Carlgo11** [comment]
@stacksjb when you checked the site's rank on Similarweb, before clicking the 2nd eligibility checkbox, what did you see?
Because to when I check it the site's ranked close to 500K https://www.similarweb.com/website/fitnesssyncer.com/

**Comment by stacksjb** [comment]
You're right, I saw it much higher somewhere else, not sure where. It is ranked high on apps and fitness categories (especially the app) but not so much on the website.

**Comment by Carlgo11** [comment]
Closing as the site doesn't meet our eligibility criteria.
