### ISSUE TITLE
Add Familysearch

### ISSUE THREAD

**Issue by stacksjb** [jdavis/twofactorauth#6925]
### Site name

FamilySearch.org

### Site URL

https://www.familysearch.org/en/

### Documentation URL

https://account.churchofjesuschrist.org/help

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [X] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [X] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

Only via Church Account (https://account.churchofjesuschrist.org/help), not for legacy accounts.

**Comment by Carlgo11** [comment]
We've had some previous requests to add religious and/or politically affiliated sites and at the moment we've decided not to list such sites.

**Comment by stacksjb** [comment]
Understood - however, Ancestry.com is listed (#1 in the Ancestry and Genealogy category, this is #2), which is why I submitted it.

Re religious/political sites; it would be worth mentioning that in the guide ([excluded categories and websites](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md)) if that is a standing decision.
