### ISSUE TITLE
Add System76

### ISSUE THREAD

**Issue by tpsapp** [jdavis/twofactorauth#6940]
### Site name

System76

### Site URL

https://system76.com/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Regions served

Globally 

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by tpsapp** [comment]
I will upload screenshots when I get home as I cannot upload to Github from my current internet access

**Comment by tpsapp** [comment]
Here are the screenshots

![system76_2fa_setup_3.png](https://user-images.githubusercontent.com/53871494/187552613-aac47869-e2bf-4b5a-8d82-863af67af677.png)
![system76_2fa_setup_2.png](https://user-images.githubusercontent.com/53871494/187552629-de4301bc-4d16-4e7e-a393-acfb21e4b85e.png)
![system76_2fa_setup_1.png](https://user-images.githubusercontent.com/53871494/187552640-aeabc1d6-b7ef-497d-aba1-1d557c8d0091.png)
![system76_2fa_login.png](https://user-images.githubusercontent.com/53871494/187552655-3982e9e8-8cff-4dd8-be15-be68b07b3bba.png)

**Comment by ghost** [comment]
![system76](https://user-images.githubusercontent.com/94222513/187600464-23fd4581-29e1-4a1c-9fe5-1bd039d948a8.png)
2FA method is incorrect. Proprietary apps are not supported; SMS and voice calls are supported.
