### ISSUE TITLE
Add CoinPayments

### ISSUE THREAD

**Issue by maltfield** [jdavis/twofactorauth#6961]
### Site name

CoinPayments

### Site URL

https://www.coinpayments.net/

### Documentation URL

https://www.coinpayments.net/supwiz-login-tfa

### Recovery Documentation URL

https://www.coinpayments.net/supwiz-login-tfa

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [X] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Regions served

They don't offer accounts to the following jurisdictions ([source](https://www.coinpayments.net/help-restricted)):

AFGHANISTAN
ALGERIA
AMERICAN SAMOA
BANGLADESH
BELARUS
BOSNIA AND HERZEGOVINA
CAMBODIA
CONGO
CONGO, DEMOCRATIC REPUBLIC
CÔTE D'IVOIRE
CUBA
ERITREA
IRAN, ISLAMIC REPUBLIC OF
IRAQ
JORDAN
LEBANON
LIBERIA
LIBYA
MYANMAR
NEPAL
NIGERIA
NORTH KOREA (DPRK)
PALESTINE, STATE OF
QATAR
RUSSIAN FEDERATION
SOMALIA
SUDAN
SYRIAN ARAB REPUBLIC
UGANDA
UNITED STATES
VANUATU
VENEZUELA, BOLIVARIAN REPUBLIC OF
YEMEN
ZIMBABWE (RHODESIA)

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

They have the option to disable username/pass/2fa completely and only allow login via trezor.

Somewhat related: they also support encrypting all their emails with your PGP key.

**Comment by Carlgo11** [comment]
Hello @maltfield,
there's a few unanswered questions regarding your issue.

1. You've checked custom hardware solution in the _Supported 2FA methods_ list. What custom hardware 2FA does CoinPayments support?
2. The documentation you linked to only mentions TOTP authentication. Could you please provide documentation for the other methods as well? If you can't, please attach a screenshot of the 2FA setup-process (with personal information blurred out).

**Comment by maltfield** [comment]
> 1. You've checked custom hardware solution in the Supported 2FA methods list. What custom hardware 2FA does CoinPayments support?

I was referring to the trezor hardware wallet, but I'm not sure exactly how that works. I don't own one.

> 2. The documentation you linked to only mentions TOTP authentication. Could you please provide documentation for the other methods as well? If you can't, please attach a screenshot of the 2FA setup-process (with personal information blurred out).

I couldn't find any more docs that enumerate this, but you select the 2FA method from a drop-down menu. Here's a screenshot:

<img src="https://images2.imgbox.com/e5/79/HYq6XdrJ_o.png" />

 * https://imgbox.com/HYq6XdrJ

**Comment by Carlgo11** [comment]
Thanks for the clarifications. As Trezor uses FIDO2 "[passwordless](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#passwordless-authentication)" it's not something we list.
