### ISSUE TITLE
Update San Francisco Fire Credit Union

### ISSUE THREAD

**Issue by maltfield** [jdavis/twofactorauth#6966]
### Site name

SF Fire CU

### Site URL

https://sffirecu.org/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

SFFire uses Alkami for online banking, and they now support 2FA over TOTP.

This ticket requests the following change:

1. Add `Software Token` (TOTP) as a 2FA option
2. Remove `Email` as a 2FA option
3. Add links to the documentation
4. Any other changes you see fit

Here's two relevant documentation pages:

 * https://sffirecu.org/how-to-use-a-2fa-application
 * https://sffirecu.org/support/frequently-asked-questions/

> **Note** Even though the documentation images show email as a 2FA option, it's not actually available in the UI

See also:

 * https://github.com/2factorauth/twofactorauth/pull/3287

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
So the currently available methods are TOTP, SMS and phone call?

**Comment by maltfield** [comment]
> So the currently available methods are TOTP, SMS and phone call?

Correct.
