### ISSUE TITLE
Add Banco Pacifico

### ISSUE THREAD

**Issue by maltfield** [jdavis/twofactorauth#6981]
### Site name

Banco Del Pacifico

### Site URL

https://www.bancodelpacifico.com/

### Documentation URL

https://www.bancodelpacifico.com/personas/servicios/servicios-generales/pacificid

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Regions served

Ecuador (only)

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

2FA is only possible via SMS or their in-house, proprietary app:

 * https://play.google.com/store/apps/details?id=com.pacifico.pacificid

**Comment by Carlgo11** [comment]
@maltfield is PacificID required for logging in or only for performing certain actions such as making transaction?

**Comment by maltfield** [comment]
@Carlgo11 unfortunately I do not know. I only have access to the documentation, same as you. If I had to guess, it's necessary for login, or at least can be configured as such.

**Comment by maltfield** [comment]
I also found this:

 * https://www.bancodelpacifico.com/BancoPacifico/media/Tutoriales/cash-management/Manual_Portal_Contratacion.pdf?ext=.pdf

From what I can tell, it does appear to be only for transactions. But it also cautions the user to make sure their timezone is correct, which suggests that their app is using TOTP rather than sending the OTP over the network, which is good.

**Comment by Carlgo11** [comment]
Without any proof that the bank uses two factor authentication rather than two factor authorization, we can’t add it to the site.
