### ISSUE TITLE
Add [site name]

### ISSUE THREAD

**Issue by danieltroger** [jdavis/twofactorauth#6992]
### Site name

Otter

### Site URL

https://otter.ai/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [ ] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [ ] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
@danieltroger you skipped a lot of steps when filling out this issue. Please be as detailed as possible when submitting an issue.

**Comment by danieltroger** [comment]
They weren't mandatory. I just wanted to add 2FA to my otter entry in 1password which seems to use this project. I'll contact their support instead, sorry for bothering you.

**Comment by Carlgo11** [comment]
This is the right place to submit websites in order for them to show up in 1Password Watchtower. We just need all the information filled out before listing the site.
