### ISSUE TITLE
Document the 2fa: search options

### ISSUE THREAD

**Issue by sn00py1310** [jdavis/twofactorauth#6995]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###
I didn't find any mention of the `2fa:` (i.e. `2fa:duo`) search options other than in some random issues or PRs. I think it should get documented somewhere, maybe in the wiki or on the website. I'd suggest naming it "Advanced search"
Feel free to share your opinions.

**Comment by Carlgo11** [comment]
Fixed in v5
