### ISSUE TITLE
Add Gab

### ISSUE THREAD

**Issue by m60irl** [jdavis/twofactorauth#6997]
### Site name

Gab

### Site URL

https://gab.com/

### Documentation URL

https://cassiusxiii.medium.com/how-to-secure-your-gab-profile-6eec64a32fbd

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by ghost** [comment]
Ummm, this may be a violation of the guidelines.

https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md
> Any site that could damage the reputation of 2fa.directory and/or lead to any controversy with either the maintainers or users, should not be listed. The group of active maintainers will decide on whether to include or exclude a site within a specific timeframe. Once an exclusion was decided upon, the site will be listed in the section below and any corresponding pull requests will be closed.
