### ISSUE TITLE
Update MercadoLivre

### ISSUE THREAD

**Issue by UnderEu** [jdavis/twofactorauth#7002]
### Site name

MercadoLivre

### Site URL

https://mercadolivre.com.br

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Site now uses Google Authenticator instead of Authy for 2FA

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
@UnderEu are you able to find any documentation or similar describing how to enable 2FA on MercadoLivre now that they don’t use Authy?

**Comment by vkwb** [comment]
> @UnderEu are you able to find any documentation or similar describing how to enable 2FA on MercadoLivre now that they don’t use Authy?

You can find it here ("Verificação em 2 etapas"):

https://www.mercadolivre.com.br/ajuda/como-fortalecer-a-seguranca-da-sua-conta_945

You also have the option to use a phone number to get the verification codes via SMS, Whatsapp message or phone call

**Comment by UnderEu** [comment]
> > @UnderEu are you able to find any documentation or similar describing how to enable 2FA on MercadoLivre now that they don’t use Authy?
> 
> You can find it here ("Verificação em 2 etapas"):
> 
> https://www.mercadolivre.com.br/ajuda/como-fortalecer-a-seguranca-da-sua-conta_945
> 
> You also have the option to use a phone number to get the verification codes via SMS, Whatsapp message or phone call

This and [the following link](https://www.mercadolivre.com.br/security/2fa) that leads to enabling the 2FA methods themselves
