### ISSUE TITLE
Update Charles Schwab *custom hardware token* can actually be standard TOTP device

### ISSUE THREAD

**Issue by colemickens** [jdavis/twofactorauth#7029]
### Site name

Charles Schwab

### Site URL

schwab.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

I actually somewhat like Charles Schwab Bank, which I can't say about any other bank.

They use some Symmantec VIP token, but it turns out its just TOTP inside.

Instructions here: https://www.reddit.com/r/personalfinance/comments/hvvuwl/using_google_auth_or_your_totp_app_of_choice_for/

Maybe someone will benefit from knowing this instead of immediately turning away.

(Also, US Financial institutes, y'all are a joke across the board, come on.)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by fletcherdodd** [comment]
I feel like with the hoop you have to jump through to get this to work outside of the Symantec VIP app it's not really worth listing as normal TOTP. Adding this as a "third-party" method would mean people _may_ possibly want other workarounds added to their favourite services and it becomes tricky to maintain.

**Comment by Carlgo11** [comment]
I agree with @fletcherdodd.
Whilst it's an interesting find; 2FA Directory isn't the right place to advertise this hack as we target general consumers and not just the tech crowd that could leverage this workaround.

As a side note, what a scumbag act of Semantic to prevent the use of third-party TOTP apps from working with their Semantic VIP system. They would definitely be fined if they did this in Europe :eyes:

**Comment by colemickens** [comment]
On the one hand, I wanted this for visibility and awareness, since I didn't know "Symantec VIP" seems to secretly mean "where there's a will, there's a way".

But I also fully understand the other vibe - I expect Schwab to be better here, too. Sadly, with the TOTP option available to me, they're the most advanced among all of the US Banks/Creditors that I've found, but that's not saying much.

Anyway, I fully understand. Thanks for considering and maintaining this resource.
