### ISSUE TITLE
Add IT Connect

### ISSUE THREAD

**Issue by 40504** [jdavis/twofactorauth#7032]
### Site name

IT Connect

### Site URL

https://itconnect.uw.edu/

### Documentation URL

https://itconnect.uw.edu/tools-services-support/access-authentication/2fa/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [X] U2F/WebAuthn security keys
- [X] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [X] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
Washington University is already listed in [washington.edu.json](https://github.com/2factorauth/twofactorauth/blob/master/entries/w/washington.edu.json)
