### ISSUE TITLE
Algolia script can't handle entry removals

### ISSUE THREAD

**Issue by Carlgo11** [jdavis/twofactorauth#7192]
Algolia.rb treats file deletions the same way as additions/modifications.
This causes the build to fail: https://github.com/2factorauth/twofactorauth/actions/runs/3804748769/jobs/6472197513#step:5:9

**Comment by phallobst** [comment]
The `--diff-filter=...` option needs to be added there, similar to some test scripts. However, I'm not use why they use `--diff-filter=Ard` and `--diff-filter=AM` respectively.

**Comment by phallobst** [comment]
Can this issue now be closed due to PR #7200?
