### ISSUE TITLE
Update OneDrive/Microsoft account

### ISSUE THREAD

**Issue by signed-log** [jdavis/twofactorauth#7217]
### Site name

OneDrive/Microsoft

### Site URL

https://onedrive.live.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

OneDrive (and by extension everything relating to an MS Account) support hardware 2FA when linking a GitHub account

----

You can link in the Account Preferences of your Microsoft Account to a GitHub account.

This will have the effect of, by default, dropping the MS password prompt once you have entered your email address, and instead redirecting you to GitHub, which has Hardware 2FA

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
Thank you for the ticket @signed-log,
even though GitHub is owned by Microsoft, the login method is what we classify as a third party SSO.
As such we don't list it for sites other than github.com.
