### ISSUE TITLE
Update outlook.com

### ISSUE THREAD

**Issue by SwarfegaGit** [jdavis/twofactorauth#7235]
### Site name

outlook.com (Microsoft)

### Site URL

https://account.microsoft.com/security?fref=home.drawers.security.security-dashboard&refd=account.microsoft.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Security Keys can now be added

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Can you provide a screenshot? I can't see the option for security keys in my account. The only thing that I see that relates to security keys is passwordless sign-in.

**Comment by SwarfegaGit** [comment]
From the Site URL I gave it goes to this page...

https://imgur.com/WI2JKvk

Then when clicking on **Advanced security options** it goes to this page

https://imgur.com/v3lkX3w

I'm not 100% sure if this is actually all that new, but I am pretty sure I have never seen key support in here before and the 2fa directory doesn't list keys as being supported either so I figured I would post it anyway.  This [article](https://support.microsoft.com/en-us/account-billing/set-up-a-security-key-as-your-verification-method-2911cacd-efa5-4593-ae22-e09ae14c6698) kinda suggests 2019.

**Comment by hkamran80** [comment]
That support article says: "You can use security keys as a passwordless sign-in method within your organization." Per [`CONTRIBUTING.md`](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#passwordless-authentication), passwordless authentication does not count as two-factor authentication.

If you can prove that the security key feature on your account is not passwordless, please re-open this issue.
