### ISSUE TITLE
Update Bitwarden

### ISSUE THREAD

**Issue by EncryptCrystal** [jdavis/twofactorauth#7251]
### Site name

Bitwarden

### Site URL

https://bitwarden.com/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

SMS and Phones Call are not supported by Bitwarden.
Only FIDO WebAuthn, YubiKey, and Duo are reserved for premium profiles (https://bitwarden.com/help/setup-two-step-login/).

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
According to the page you linked to SMS and phone calls are still supported with Duo on Team and Enterprise accounts
