### ISSUE TITLE
Add MyPrimobox

### ISSUE THREAD

**Issue by EncryptCrystal** [jdavis/twofactorauth#7268]
### Site name

MyPrimobox

### Site URL

www.myprimobox.net

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

To set up 2FA :

Step 1 : 
![image](https://user-images.githubusercontent.com/52292872/212468859-62e96166-31e5-4583-9c8d-2f3332320ce9.png)

Step 2 : 
![image](https://user-images.githubusercontent.com/52292872/212468910-b48ed7df-0a42-4ad5-bf0d-7423e2acd697.png)

Step 3 : 
![image](https://user-images.githubusercontent.com/52292872/212468938-17071715-1e2f-4615-99b2-ecbd688d436a.png)

**Comment by hkamran80** [comment]
Can you provide evidence of TOTP 2FA?

**Comment by EncryptCrystal** [comment]
I have this image from the login page :

![image](https://user-images.githubusercontent.com/52292872/212495240-1e86efa2-c0f1-45b2-9e56-26b015b8f2db.png)
