### ISSUE TITLE
Update Microsoft Azure

### ISSUE THREAD

**Issue by henrybelk** [jdavis/twofactorauth#7348]
### Site name

Microsoft Azure

### Site URL

portal.azure.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Microsoft Azure supports hardware (hardware OTP tokens and FIDO2 security keys). Their software supports Microsoft Authenticator as well as 3rd party providers (e.g. I have configured Duo as a MFA provider for my users).

- https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods
- https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-mfa-howitworks

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
This seems to be FIDO2 "[passwordless](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#passwordless-authentication)", a good alternative to Password + 2FA but not something which we regard as actual 2FA/MFA. Whilst there are papers arguing for FIDO2 to be regarded as technically being 2FA/MFA by itself, our recent [Twitter poll](https://twitter.com/2faorg/status/1559252986244861954) showed a clear majority of users don't share this view, causing us to take this stance.
Should the public perception change we're open to change this ruling.

**Comment by henrybelk** [comment]
Just because they don't think it isn't doesn't mean it isn't. A security key is 2FA, a cryptographic device that stores a private key that authenticates to the public cert on the provider. It satisfies:

1. Something you have (the security key) +
2. Something you are (biometric with fingerprint to unlock the security key) OR
3. Something you know (PIN required to unlock the security key)

Just because you have the physical key (1FA), you can't get into the account without satisfying the other requirement to unlock the private key (something you are or know) (1FA +1FA = 2FA).

Regardless they also support hardware OTP tokens as well.

**Comment by Carlgo11** [comment]
Thanks for your input @henrybelk.
If you want to add OATH to Azure you can create a PR and we'll look at it as soon as we can. Otherwise someone else will create a PR to implement it at a later date.

Regarding FIDO2, there is currently an [open issue](#6388) regarding FIDO2 and if you have the expertise we'd love some help on how to implement FIDO2 into our site. Particularly we're interested in how to verify how sites treat user verification and user presence.
There are also forks of 2fa.directory, like [dongleauth.info](https://github.com/Nitrokey/dongleauth), that list FIDO2 support which might be of interest to you.

**Comment by henrybelk** [comment]
I glanced at the other issue page (#6388) and saw Jeremy who used to be at NIST. With NIST regarding FIDO2/WebAuthn as [strong MFA](https://csrc.nist.gov/csrc/media/Presentations/2022/multi-factor-authentication-and-sp-800-63-digital/images-media/Federal_Cybersecurity_and_Privacy_Forum_15Feb2022_NIST_Update_Multi-Factor_Authentication_and_SP800-63_Digital_Identity_%20Guidelines.pdf) as well as CISA listing FIDO2/WebAuthn as [phishing-resistant MFA](https://www.cisa.gov/sites/default/files/publications/fact-sheet-implementing-phishing-resistant-mfa-508c.pdf), they are the sources that I was going to point more to. FIDO2 used asymmetric key cryptography which is currently the strongest form of MFA.

As far as implementing, I am not a dev unfortunately. I have come across https://webauthn.io/ before. They have guides to implement FIDO2/WebAuthn on several librares which may help if you haven't seen it before.

**Comment by Carlgo11** [comment]
After further investigating, it looks like you're referring to Azure Active Directory, an Identity Management product in Azure, and not the Microsoft Azure authentication system itself.
As such OATH OTP can't be added to the Microsoft Azure entry on 2FA Directory.

If this is incorrect please let me know.
