### ISSUE TITLE
Update [1Password]

### ISSUE THREAD

**Issue by KqZPVpwqDsCeyPuUcQTf** [jdavis/twofactorauth#7369]
### Site name

1Password

### Site URL

https://1password.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Hi. As per 2023-01-24, it's possible to just use security key as 2FA on 1Password. Check out release notes for build 1428 (webpage) here:
https://app-updates.agilebits.com/product_history/B5#v1428

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
@KqZPVpwqDsCeyPuUcQTf we already list 1Password as supporting FIDO U2F keys.

**Comment by KqZPVpwqDsCeyPuUcQTf** [comment]
Thanks for replying.
I mean, you no longer need to have enabled TOTP 2FA in order to be using keys. Now you can just use keys.
