### ISSUE TITLE
Image hotlinking disabled

### ISSUE THREAD

**Issue by Hacksore** [jdavis/twofactorauth#7381]
hey all 👋! This is an awesome project and I used it to make focused list for hardware tokens.

App: https://u2f.vercel.app
Code: https://github.com/Hacksore/u2f

However, seems recently hotlinking of images was blocked on the CF side.

Was there too much traffic caused by hotlinking or could it be reinstated?

Example image:
https://api.2fa.directory/icons/a/alliantcreditunion.org.svg

**Comment by Carlgo11** [comment]
Hello @Hacksore,
as company logos are part of the company's trademarks it's not something we feel comfortable distributing through our API.

Regarding your website, please be aware that our license requires attribution and the inclusion of our license. You can read more about the MIT License [here](https://tldrlegal.com/license/mit-license).
