### ISSUE TITLE
Update Coinbase

### ISSUE THREAD

**Issue by TheGo2SWATking** [jdavis/twofactorauth#7395]
### Site name

Coinbase

### Site URL

https://coinbase.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Coinbase's U2F/security key implementation is broken for registering new security keys. Until this is resolved their indicated support for U2F on 2fa.directory should be removed.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
Any official communication from Coinbase supporting the claim that U2F is broken?

**Comment by TheGo2SWATking** [comment]
No, I've been trying to get them to acknowledge it's broken but their support system just sends canned replies back. I've tried different keys, different browsers, in incognito mode, different computers, etc. I can only assume it's broken and they aren't interested in fixing it.
![1](https://user-images.githubusercontent.com/14121277/218283778-7dd1dbc6-4640-4654-a75e-618a33ab43e8.png)
![2](https://user-images.githubusercontent.com/14121277/218283781-db25d956-1919-4fa4-b6a3-a973b315f2ef.png)
![3](https://user-images.githubusercontent.com/14121277/218283782-18fcef72-bd39-484a-861c-a7138b318ea8.png)
![4](https://user-images.githubusercontent.com/14121277/218283783-6f52b71d-1977-4137-a027-8d8a5156b69b.png)
![5](https://user-images.githubusercontent.com/14121277/218283850-f049b522-b993-43c8-b538-2851aba001a5.png)
![6](https://user-images.githubusercontent.com/14121277/218283787-6864163e-8a03-415c-9c9b-6652706fcc87.png)
![7](https://user-images.githubusercontent.com/14121277/218283788-bd3b5982-4568-4f74-8deb-d508696b4bdf.png)
![8](https://user-images.githubusercontent.com/14121277/218283789-320aa6a4-8871-4985-84f6-0b135b482751.png)
![9](https://user-images.githubusercontent.com/14121277/218283790-e046a794-eef6-40ee-9330-06a16fd80a77.png)

**Comment by Carlgo11** [comment]
@TheGo2SWATking I just tried to add my U2F key and it worked fine. Not sure why you're having issues but adding security keys to Coinbase does work.

![Screenshot](https://user-images.githubusercontent.com/3535780/218343858-c4d604f9-ad2c-4599-9798-ac5602b5e554.png)

**Comment by TheGo2SWATking** [comment]
> @TheGo2SWATking I just tried to add my U2F key and it worked fine. Not sure why you're having issues but adding security keys to Coinbase does work.
> 
> ![Screenshot](https://user-images.githubusercontent.com/3535780/218343858-c4d604f9-ad2c-4599-9798-ac5602b5e554.png)

Interesting that it works on mobile, but not on desktop. I suppose I could try on mobile, but I'm more leaning towards deleting my account with them at this point.

**Comment by Carlgo11** [comment]
Best of luck! I imagine their app may also be a possible way to enable U2F.

I'm going to close this issue now as we've established Coinbase does offer 2FA through FIDO U2F security keys (although it doesn't work for you for some reason).
