### ISSUE TITLE
bkashape@gmail.com

### ISSUE THREAD

**Issue by arfanakash446** [jdavis/twofactorauth#7435]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<reference anchor="RFC9346" target="https://www.rfc-editor.org/info/rfc9346">
<front>
<title>IS-IS Extensions in Support of Inter-Autonomous System (AS) MPLS and GMPLS Traffic Engineering</title>
<author fullname="M. Chen" initials="M." surname="Chen"/>
<author fullname="L. Ginsberg" initials="L." surname="Ginsberg"/>
<author fullname="S. Previdi" initials="S." surname="Previdi"/>
<author fullname="D. Xiaodong" initials="D." surname="Xiaodong"/>
<date month="February" year="2023"/>
<abstract>
<t>This document describes extensions to the Intermediate System to Intermediate System (IS-IS) protocol to support Multiprotocol Label Switching (MPLS) and Generalized MPLS (GMPLS) Traffic Engineering (TE) for multiple Autonomous Systems (ASes). It defines IS-IS extensions for the flooding of TE information about inter-AS links, which can be used to perform inter-AS TE path computation.</t>
<t>No support for flooding information from within one AS to another AS is proposed or defined in this document.</t>
<t>This document builds on RFC 5316 by adding support for IPv6-only operation.</t>
<t>This document obsoletes RFC 5316.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="9346"/>
<seriesInfo name="DOI" value="10.17487/RFC9346"/>
</reference>

**Comment by Carlgo11** [comment]
Interesting.
