### ISSUE TITLE
Update Bank of America

### ISSUE THREAD

**Issue by thegushi** [jdavis/twofactorauth#7438]
### Site name

Bank Of America

### Site URL

https://bofa.com

### Update reason

Other (please describe below).

### Additional information

Hardware-based 2fa falls back to only sms/phone based 2fa if using their app.  This feels worthy of a warning on the main page.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Do you mean they disable hardware 2FA if you use their app, or they only allow SMS/call 2FA to log into their app?

**Comment by thegushi** [comment]
Sorry for delay.  Yes, only SMS/Call are allowed for the app.  They seem to ignore that both iOS has built-in fido/u2f (iOS calls them Passkeys, and they are iCloud-shareable), and that there are iOS-compatible Yubikeys.  

Worse, their app doesn't seem to care that "Touch ID" is also a form of 2fa, so even if you have Touch ID turned on, it will attempt to phone/SMS you.

Trying to load their mobile app in a browser (i.e. Safari on iOS) gives you this 2008-level nightmare:

![image](https://user-images.githubusercontent.com/1140008/221439432-8e5b1554-9254-4f07-a8c7-9522bada58e9.png)

(edit: correct iOS capitalization)

**Comment by hkamran80** [comment]
Thanks for the clarification!
