### ISSUE TITLE
Update AT&T

### ISSUE THREAD

**Issue by evlnte** [jdavis/twofactorauth#7465]
### Site name

AT&T

### Site URL

https://www.att.com

### Update reason

Other (please describe below).

### Additional information

I find that it only supports 2FA with SMS as long as the phone line is through AT&T Wireless. I claims to send verification codes to other carriers, but I never receive them in order to activate the 2FA feature.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
We need some further proof to change the existing listing. If you could contact their support and get them to confirm that they don't support SMS 2FA via other carriers or get a second person to confirm it works as you've outlined, we'd be able to proceed.

**Comment by Carlgo11** [comment]
Closing due to author inactivity.
