### ISSUE TITLE
Add Throne

### ISSUE THREAD

**Issue by decimic** [jdavis/twofactorauth#7508]
### Site name

Throne

### Site URL

https://throne.me

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

![FrW1EngXwBMypsz](https://user-images.githubusercontent.com/35397773/229683382-be28a7b3-80ae-418d-a125-e6d0480465f0.jpg)

**Comment by decimic** [comment]
I just realized something. Throne recently updated their domain from throne.me to throne.com.  This change is rather recent, so the new domain is not within the top 200,000 sites, though the old domain is.  Throne.me now redirects to throne.com.
[Source](https://twitter.com/official_throne/status/1639331175582842880)

**Comment by Carlgo11** [comment]
As the SimilarWeb rank is above 200K, the site is not eligible to be listed.
You can re-open the issue if/when it meets all eligible criteria.
