### ISSUE TITLE
Update [weltsparen.de] SMS available and new logo

### ISSUE THREAD

**Issue by BaumiCoder** [jdavis/twofactorauth#7561]
### Site name

Weltsparen

### Site URL

https://www.weltsparen.de/

### Update reason

It now supports 2FA., Its logo has changed.

### Additional information

1. It now supports SMS. They call it "mTan" You don't need it for login, but for action like [investing](https://kundenservice.weltsparen.de/hc/de/articles/7201711367314-Wie-kann-ich-eine-Geldanlage-t%C3%A4tigen-) or to [transfer money back to your bank account](https://kundenservice.weltsparen.de/hc/de/articles/7209358106002-Wie-kann-ich-Geld-auf-mein-Referenzkonto-auszahlen-%C3%BCberweisen-) (links go to the german webhelp). Is that a restriction, which should be metioned in the "notes" field?
2. The logo is now blue instead of orange. (Where are you getting the new logo without getting copyright problem?)

If someone can answer my question to the changes, I maybe will create a pull request on my own.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
The way you described mTan, it's not two-factor authentication. It's [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization).

We get the logo from the website that is being added.

**Comment by BaumiCoder** [comment]
Thank you for your fast answer.
I already supposed that this isn't a full authentication, but I wasn't sure how to name it. Now I got it.
I will update the logo and create an pull request.
