### ISSUE TITLE
Update OpenAI

### ISSUE THREAD

**Issue by anonymoose0** [jdavis/twofactorauth#7571]
### Site name

OpenAI

### Site URL

openai.com

### Update reason

It now supports 2FA.

### Additional information

OpenAI now supports software-based 2FA. The option can be found under data controls in settings (at least in ChatGPT). Additionally, the feature appears to have been announced at [https://trust.openai.com/](url). The documentation can be found at the same site, but appears to be locked behind some sort of privilege control where access needs to be requested for what seems to be auditing purposes.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
@anonymoose0 OpenAI is already listed as supporting 2FA so what is it that you want to change?

**Comment by anonymoose0** [comment]
@Carlgo11 I was looking at the 2fadirectory website and it hadn't been updated to say as such, so either I had an older version of the site loaded (which is odd because I had pulled it up today) or it was updated as I was submitting my issue. Sorry for the trouble.

**Comment by Carlgo11** [comment]
No worries @anonymoose0.
We use a lot of edge server caching so that content is loaded faster to users. A side effect of that is that some people may not receive the most recent website version.
#7569 added 2FA to OpenAI 15 hours ago so within a day or so you should see it.
