### ISSUE TITLE
Add Plisio

### ISSUE THREAD

**Issue by AdPlisio** [jdavis/twofactorauth#7587]
### Site name

Plisio

### Site URL

https://plisio.net

### Documentation URL

https://plisio.net/faq/how-to-enable-two-factor-authorization

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [X] Email tokens

### Eligibility

- [ ] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
@AdPlisio could you link to an SVG version of your favicon?

**Comment by AdPlisio** [comment]
@Carlgo11 https://plisio.net/v2/images/logo-color.svg

**Comment by Carlgo11** [comment]
That's the logo, we display icons.

**Comment by AdPlisio** [comment]
@Carlgo11 only this not svg https://plisio.net/favicon.ico

**Comment by Carlgo11** [comment]
Okay. What about this version?

<img src="https://github.com/2factorauth/twofactorauth/assets/3535780/21537cda-71df-404c-902c-34ec521a1988" width="64px"/>

**Comment by AdPlisio** [comment]
@Carlgo11 looks great

**Comment by Carlgo11** [comment]
@AdPlisio do you represent Plisio or are you just a customer?

Because I found some irregularities when trying to figure out Plisio's regions of operations.
There's no adherence to GDPR which means the service most likely isn't intended for the EU/UK market.
Furthermore, there are no _know your customer_ requirements at registration which would lead me to conclude Plisio isn't worried about the state department raiding them for helping funnel money for the North Koreans.
That would leave very few countries where the service would be legal.

**Comment by AdPlisio** [comment]
@Carlgo11 How do GDPR and two-factor authentication relate to each other?

**Comment by Carlgo11** [comment]
It doesn't. I'm just trying to find which regions to list the service in.

That said, websites that serve illegal content or promote illegal activities cannot be listed in this repository so if the service acts as a Bitcoin tumbler or doesn't comply with money laundering and terrorist financing prevention laws, it cannot be listed on 2FA Directory.
