### ISSUE TITLE
Access to logo images not possible - protected 403 strict-origin-when-cross-origin

### ISSUE THREAD

**Issue by gutschik** [jdavis/twofactorauth#7675]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

When trying to access the logos provided by the json api from the browser, the server responds with '403 strict-origin-when-cross-origin'. 
![image](https://github.com/2factorauth/twofactorauth/assets/29476/26ca9b78-d7f5-45d8-93c0-4d6555cdfba6)
The question is, can our domain be whitelisted or do we have to proxy the images ?

**Bug reproduction:**

https://codepen.io/gutschik/full/yLQMggj

**Impacted devices:**

Every modern browser. 

**Expected behavior:**

The logos should be accessible - at least for sponsors of the project 😉

**Additional information:**

**Comment by hkamran80** [comment]
See #7381

**Comment by gutschik** [comment]
thanks, @hkamran80 - I don't know why I did not come across this issue https://github.com/2factorauth/twofactorauth/issues/7381. 

In my opinion, I think it's reasonable that you protect the images due to possible trademark conflicts, especially when thinking of companies like 🍏  

but on the other hand, I'd suggest to mention this circumstance somewhere in the api [documention](https://2fa.directory/api/) AND provide a workaround. 
 
![Screenshot 2023-07-06 at 09 40 42](https://github.com/2factorauth/twofactorauth/assets/29476/ca13d8b9-3f8b-4ef1-bf95-3b021e8950ad)

The workaround could be accessing the images via github, where they can be accessed anyway
So instead of 
```
https://api.2fa.directory/icons/0/000webhost.com.svg
```
get 
```
https://raw.githubusercontent.com/2factorauth/twofactorauth/master/img/0/000webhost.com.svg
```

**Comment by Carlgo11** [comment]
Hello @gutschik,
thank you for your suggestions!

We will definitely add a note in the documentation about why we don't serve icons through our API.

Regarding your workaround, it is of course always possible to fetch the icons directly from GitHub but doing so means things might break if we make changes to the repository structure. As such, it's not safe for production like our API and thus not something that we'll advice doing.

If you're happy with the workaround that's great but please be aware that things might break in the future.


Regarding serving icons just to sponsors, we're very grateful for any donations but putting the icons behind a paywall would legally be even worse than distributing it to everyone as now we'd be doing it for a profit. 😅

**Comment by gutschik** [comment]
> Regarding your workaround, it is of course always possible to fetch the icons directly from GitHub but doing so means things might break if we make changes to the repository structure. As such, it's not safe for production like our API and thus not something that we'll advice doing.

Hello @Carlgo11 - what would you advice in order to display the logos?

**Comment by Carlgo11** [comment]
As noted earlier, we don't provide any mechanism for distributing the icons to third parties because of copyright reasons. Most third parties, that need icons and use our data, fetch icons/logos from other sources, like through favicon scaping or from their own database of icons.

If you require icons, I suggest you look into one of those options or use the workaround you mentioned if you find the risk of future changes acceptable. There also might be services specialized in company logo distribution online but that is something that's out of scope for our objective.

Best of luck!
