### ISSUE TITLE
Add Doctolib France

### ISSUE THREAD

**Issue by freshgoods** [jdavis/twofactorauth#7686]
### Site name

Doctolib

### Site URL

https://www.doctolib.fr/

### Documentation URL

https://doctolibpatient.zendesk.com/hc/fr/articles/360021300860

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Regions served

France

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

Category: Health
Customer-facing web site (different to the "professional" one)

**Comment by kmpoppe** [comment]
Will be grouped together in one entry (as per `additional-domains` rule), assigned creating the entry to myself as I need to check for a SVG'd logo directly from DTL.
