### ISSUE TITLE
Add epayslips.co.uk

### ISSUE THREAD

**Issue by joshdaws0n** [jdavis/twofactorauth#7692]
### Site name

ePayslips

### Site URL

https://epayslips.co.uk

### Documentation URL

Provided by employer

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Regions served

United Kingdom

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by joshdaws0n** [comment]
![unnamed](https://github.com/2factorauth/twofactorauth/assets/30846302/d81db8bf-c437-4eb6-912f-50638ca80dcb)

Logo attached

**Comment by hkamran80** [comment]
Could you attach some screenshots of the MFA setup and/or login screen?

**Comment by spellbind0127** [comment]
I created the pull request #7714 for this issue. I am having trouble finding an svg image

**Comment by phallobst** [comment]
Closed by #7753
