### ISSUE TITLE
changes made on github aren't being reflected on the 2fa.directory website

### ISSUE THREAD

**Issue by spellbind0127** [jdavis/twofactorauth#7709]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

changes that are made to 2fa.directory don't seem to be reflected on https://2fa.directory for example the change https://github.com/2factorauth/twofactorauth/pull/7704 isn't reflected 
<img width="1271" alt="Screenshot 2023-08-10 at 5 40 23 PM" src="https://github.com/2factorauth/twofactorauth/assets/131718514/1fa00e9f-e9f3-40ff-a40a-0932627558f1">

**Bug reproduction:**

make a change on the github 

**Impacted devices:**

**Expected behavior:**

you expect this change to be reflected on https://2fa.directoy
unfortunently the change isn't reflected

**Additional information:**

**Comment by hkamran80** [comment]
Our cache causes updates to take a little while to update. JSON updates take anywhere from ten minutes to about a day to update, and logo updates take longer. In the case of Tutanota, I know for a fact that it's been updated. Try force-reloading the page. On macOS in Firefox, the keyboard shortcut is Shift+Command+R.
