### ISSUE TITLE
Update University of Colorado Boulder

### ISSUE THREAD

**Issue by spellbind0127** [jdavis/twofactorauth#7718]
### Site name

University of Colorado Boulder

### Site URL

https://www.colorado.edu/

### Update reason

Other (please describe below).

### Additional information

As a undergrade who goes to the goes to the University of Colorado Boulder I do not think they should qualify for 2fa.
I am rarely if ever asked for a 2fa code when I sign in to outlook at Cu (this includes if you use a vpn. BuffPortal which is what I use to access basically everything as a student doesn't support 2fa.
<img width="1271" alt="Screenshot 2023-08-18 at 1 24 32 PM" src="https://github.com/2factorauth/twofactorauth/assets/131718514/4bc97c18-aeb8-4cd7-b193-521d315b9ed1">
)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
CU Boulder's Office of Information Technology [says that](https://oit.colorado.edu/services/identity-access-management/multi-factor-authentication):
> Yes, everyone using CU Boulder's Microsoft 365 instance will be required to use MFA. 

Could it be that the Buff Portal isn't part of their M365 instance, and therefore not backed by their MFA?

**Comment by spellbind0127** [comment]
As someone who goes to Cu boulder I can confirm that you don't login using M365 to access 90% percent of what students access. For that Cu Uses there own SSO solution that doesn't support MFA

**Comment by hkamran80** [comment]
Well that's frustrating. In that case, do you want to add a note to the entry?

**Comment by spellbind0127** [comment]
I think we should remove it as having 2fa. As I have never encountires the "2fa" that they have "enabled" on their microsoft products.

**Comment by spellbind0127** [comment]
For your convenience, your sign-in session on your regular devices will not require you to login or use multi-factor often, but it will protect your account if any suspicious attempts to login are detected.  (Thats not 2fa in my book that we have another way to verify you when their suspicion activity on your account)

**Comment by Carlgo11** [comment]
Looks like [CAS](https://www.apereo.org/projects/cas) is used with a private oauth server, although why anyone would want to go through the hassle of setting up their own SSO/SAML service is beyond my comprehension.

CAS does provide [modules for MFA](https://apereo.github.io/cas/6.6.x/mfa/Configuring-Multifactor-Authentication.html) but you're saying no MFA is provided at all when authenticating through the non-MS365 SSO portal?

**Comment by spellbind0127** [comment]
yes but I am also saying that they don't have 2fa in general because i never get asked for a 2nd factor. (even login in with a vpn on in incognito mode)

**Comment by spellbind0127** [comment]
so yes I am accusing the school of lying about enabling 2fa.

**Comment by hkamran80** [comment]
Wow.
