### ISSUE TITLE
Add nutmeg.com

### ISSUE THREAD

**Issue by KanchiMoe** [jdavis/twofactorauth#7720]
### Site name

Nutmeg

### Site URL

https://www.nutmeg.com/

### Documentation URL

https://support.nutmeg.com/?article=115000495111-How-to-set-up-and-manage-2-step-verification

### Recovery Documentation URL

https://support.nutmeg.com/?article=115000495111-How-to-set-up-and-manage-2-step-verification (bottom of page)

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Regions served

UK

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

Nutmeg is an online investment management service.

**Comment by hkamran80** [comment]
Nutmeg is already in 2fa.directory. The entry is [visible here](https://github.com/2factorauth/twofactorauth/blob/master/entries/n/nutmeg.com.json).
