### ISSUE TITLE
Remove Wikipedia

### ISSUE THREAD

**Issue by koitsu** [jdavis/twofactorauth#7726]
### Site name

Wikipedia

### Site URL

https://www.wikipedia.org/

### Removal reason

Other (please describe below).

### Additional information

Original report: https://github.com/bitwarden/clients/issues/6122

Recommendation link per 2fa.directory: https://meta.wikimedia.org/wiki/Help:Two-factor_authentication

Wikipedia/Wikimedia only lets you enable 2FA on your Wikipedia account if you are "super special".  **Most users and generic contributors _do not_ fall into this category.**  The referenced instructions tell you to visit https://meta.wikimedia.org/wiki/Special:Manage_Two-factor_authentication (what they call "Special:OATH" -- which is badly named (it should be OAUTH not OATH -- kind of ironic considering how nitpicky Wikipedia is)).  Upon doing so, you will be greeted with this error:

> Unauthorized
> You do not have permission to enable two-factor authentication, for the following reason:
> The action you have requested is limited to users in one of the groups: [Administrators](https://meta.wikimedia.org/wiki/Meta:Administrators), [Interface administrators](https://meta.wikimedia.org/wiki/Meta:Interface_administrators), [Bureaucrats](https://meta.wikimedia.org/wiki/Meta:Bureaucrats), [Oversighters](https://meta.wikimedia.org/wiki/Meta:Oversighters), [Importers](https://meta.wikimedia.org/wiki/Help:Import), [Transwiki importers](https://meta.wikimedia.org/wiki/Meta:Transwiki_importers), [Central notice administrators](https://meta.wikimedia.org/wiki/Meta:Central_notice_administrators), [Global renamers](https://meta.wikimedia.org/wiki/Special:MyLanguage/Global_renamers), [OAuth administrators](https://meta.wikimedia.org/wiki/Meta:OAuth_administrators), [Translation administrators](https://meta.wikimedia.org/wiki/Meta:Translation_administrators), [WMF Office IT](https://meta.wikimedia.org/wiki/Meta:WMF_Office_IT), [WMF Trust and Safety](https://meta.wikimedia.org/wiki/Meta:WMF_Trust_and_Safety), [CheckUsers](https://meta.wikimedia.org/wiki/Meta:CheckUsers).

I state this purely aware that the 2fa.directory site has a warning on it that says (also with the OATH typo, haha):

> Currently limited to administrators (and users with admin-like permissions like interface editors), bureaucrats, checkusers, oversighters, stewards, edit filter managers and the OATH-testers global group.

If there is a better way to present this information to users (i.e. "may or may not apply to you"), that'd be fine too, **but at present companies like Bitwarden using 2fa.directory treat ANY entry like a yes/no condition.**  I'm trying to remain practical about this.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by koitsu** [comment]
Closing this issue because now that I actually look at [2fa.directory itself](https://2fa.directory/) these kinds of limitations are presented clearly in the UI there.

The problem is with Bitwarden in their Vault site not showing this information and instead treating 2FA/TOTP as a yes/no feature and not presenting the Exceptions/Restrictions details to their customers.

**Comment by hkamran80** [comment]
Heads up that OATH isn't a typo. It's the [Initiative for Open Authentication](https://wikipedia.org/wiki/Initiative_for_Open_Authentication), which is not related to OAuth. TOTP, HOTP, and OCRA are part of [their specifications](https://openauthentication.org/specifications-technical-resources/).
