### ISSUE TITLE
Fidelity Netbenefits is SMS or email 2FA only

### ISSUE THREAD

**Issue by schwit61** [jdavis/twofactorauth#7727]
### Site name

Fidelity NetBenefits

### Site URL

https://nb.fidelity.com/

### Documentation URL

https://nb.fidelity.com/public/nb/default/resourceslibrary/articles/securityfaqlearnmore

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [X] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Eligibility

- [ ] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [ ] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

Fidelity Investments permits the use of Symantec 2FA app, Fidelity NetBenefits does not

**Comment by hkamran80** [comment]
Is NetBenefits separate from the main Fidelity login?

**Comment by schwit61** [comment]
Yes. Almost like 2 different companies. 

 

If I try to log in to my Fidelity Netbenefits account on the Fidelity Investments page, it redirects me to the Fidelity Netbenefits login panel.

 





 

 

Fidelity Investments Profile Security




 

Fidelity Netbenefits Profile Security
