### ISSUE TITLE
Add https://mongodb.com/

### ISSUE THREAD

**Issue by SorkoPiko** [jdavis/twofactorauth#7752]
### Site name

MongoDB

### Site URL

https://www.mongodb.com/

### Documentation URL

https://www.mongodb.com/docs/atlas/security-multi-factor-authentication/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [X] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by hkamran80** [comment]
MongoDB is already present. The JSON entry is [available here](https://github.com/2factorauth/twofactorauth/blob/master/entries/m/mongodb.com.json).

**Comment by SorkoPiko** [comment]
Oh. I couldn't find it earlier. Now I can. Sorry.

**Comment by hkamran80** [comment]
No worries!
