### ISSUE TITLE
Add Timly

### ISSUE THREAD

**Issue by dominikconrads** [jdavis/twofactorauth#7775]
### Site name

Timly Software

### Site URL

https://timly.com/

### Documentation URL

https://timly.com/en/docs/technical-support/how-do-i-activate-two-factor-authentication-2fa-images/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Regions served

Europe

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
Hi @dominikconrads,
thanks for showing interest in the project!
I just want to confirm that you've verified that [timly.com](https://timly.com/) is ranked within the top 200K global sites on [Similarweb](https://www.similarweb.com/website/timly.com) as you indicated by clicking that checkbox.

**Comment by dominikconrads** [comment]
I checked the checkbox because I just assumed that the page is ranked accordingly. In general, it would be better for the project to include more sites that support 2FA than fewer, right? Especially if it is a provider who sells his services mainly to customers of a limited region.
After all, there are password managers that rely on your directory to show users if 2FA is available for a login.

**Comment by Carlgo11** [comment]
Our guidelines on [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) require new entries to have a global rank of 200,000 or less on [Similarweb](https://www.similarweb.com/website/).
This requirement is in place because maintaining the lists takes time, and a list of all websites on the internet isn't feasible.

Unfortunately, as the site you want to add is ranked above 200,000, it doesn't meet our guidelines and thus can't be added. If the site rises in popularity in the future and is ranked below 200,000 on Similarweb, this issue can be reopened.

**Comment by dominikconrads** [comment]
I could follow the reasoning insofar as you don't want to arbitrarily add websites if they also don't support 2FA. However, this is about the security of the users and as I said before, there are password managers that rely on your directory. That's why I find this restriction nonsensical to be honest. The site in question will never achieve such relevance because its product is offered exclusively in a limited market. But you only consider the global rank of a website. Really a pity for the whole project.
