### ISSUE TITLE
Update Truist

### ISSUE THREAD

**Issue by schwit61** [jdavis/twofactorauth#7790]
### Site name

truist.com

### Site URL

https://dias.bank.truist.com/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Truist login MFA is SMS, phone call or email. 

![truist_MFA](https://github.com/2factorauth/twofactorauth/assets/34592977/f0ae340a-d78d-439e-aeaa-1e68c123df6f)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Does this MFA prompt appear every time you log in? Could you please attach some screenshots of the 2FA setup process or management screen? Please blur or crop out any personal or sensitive information.

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

**Comment by schwit61** [comment]
MFA happens every time
