### ISSUE TITLE
Add Sagawa Express

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#7835]
### Site name

Sagawa Express

### Site URL

https://www.sagawa-exp.co.jp/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [X] Email tokens

### Regions served

Japan

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [x] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

Category: Post and Shipping

---
Update 2024-03-12: Simularweb
https://www.similarweb.com/website/sagawa-exp.co.jp/#overview

**Comment by fletcherdodd** [comment]
Closed as the user no longer exists and there is no link to any documentation or screenshots of 2FA methods.
