### ISSUE TITLE
Update Seznam.cz

### ISSUE THREAD

**Issue by Fejby** [jdavis/twofactorauth#7840]
### Site name

Seznam.cz

### Site URL

https://seznam.cz/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Seznam.cz started to support 2FA via any TOTP application.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Please attach some screenshots of the 2FA setup process, login process, or management screen. Please blur or crop out any personal or sensitive information. Alternatively, please add a link to a documentation page.

**Comment by Fejby** [comment]
![image](https://github.com/2factorauth/twofactorauth/assets/73366988/d1e380b8-f025-4925-8b50-1ef991937a7e)
![image](https://github.com/2factorauth/twofactorauth/assets/73366988/f972771f-156c-4c6a-a5c7-d7a13c8af24b)
![image](https://github.com/2factorauth/twofactorauth/assets/73366988/55c992f6-4404-4ed0-a15d-089a4bcd5fb6)
![image](https://github.com/2factorauth/twofactorauth/assets/73366988/64d6974a-8c01-4a84-a6ee-5360857f2d67)
![image](https://github.com/2factorauth/twofactorauth/assets/73366988/804004f7-e9e2-4918-8338-e4c1bec408f4)
![image](https://github.com/2factorauth/twofactorauth/assets/73366988/eb8670c0-12ab-442c-b667-339fcfd9482d)
 
 Documentation [here](https://napoveda.seznam.cz/cz/zapnuti-dvoufazoveho-overeni/)

**Comment by hkamran80** [comment]
Closed by #7842
