### ISSUE TITLE
Add MyChart

### ISSUE THREAD

**Issue by NoneTheFewer** [jdavis/twofactorauth#7844]
### Site name

MyChart

### Site URL

https://mychart.org/

### Documentation URL

https://mychart.org/Help?topic=two-factor-auth

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by hkamran80** [comment]
MyChart is already a part of 2FA Directory. The JSON file is [here](https://github.com/2factorauth/twofactorauth/blob/master/entries/m/mychart.com.json).
