### ISSUE TITLE
Add Bitskins

### ISSUE THREAD

**Issue by 3kh0** [jdavis/twofactorauth#7863]
### Site name

Bitskins

### Site URL

https://bitskins.com

### Documentation URL

https://bitskins.com/blog/why-do-we-require-2fa-for-withdrawals/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by fletcherdodd** [comment]
Hi @3kh0,
Does the site require you to use 2FA when logging into it or only when you want to make a withdrawal? If it's the latter under the definitions [located here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) it would not be considered 2FA.

**Comment by 3kh0** [comment]
> Hi @3kh0,
> 
> Does the site require you to use 2FA when logging into it or only when you want to make a withdrawal? If it's the latter under the definitions [located here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) it would not be considered 2FA.

I enabled it on my account, and logging in with Steam, it wants me to enter in a two FA code generated by my app.
