### ISSUE TITLE
Update Crowdin

### ISSUE THREAD

**Issue by windmueller** [jdavis/twofactorauth#7871]
### Site name

Crowdin

### Site URL

https://crowdin.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Crowdin now supports U2F security keys. However, the documentation has not been updated.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
If no documentation is available or you can't find it, please attach screenshots of the 2FA setup and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

**Comment by windmueller** [comment]
![Bildschirmfoto vom 2023-12-20 10-59-19](https://github.com/2factorauth/twofactorauth/assets/1096199/3c9c4732-1797-4ca8-af06-a59587a1f609)
