### ISSUE TITLE
Similarweb Requires Account to Check Rankings

### ISSUE THREAD

**Issue by soodaayush** [jdavis/twofactorauth#7878]
Hello,

Whenever I want to add a website, I go to Similarweb to check if it is in the top 200k websites. When I try to do that it requires me to make an account and give information such as my phone number. I am not comfortable with doing this, especially since I am just using this to check a website ranking, which used to require no account.

Is there an alternative solution we could possibly use, or is there a workaround to this account requirement?

**Comment by Carlgo11** [comment]
Hello @soodaayush,
try going entering the url `https://similarweb.com/website/(domain)` where `(domain)` is the website you want to check. That way it shouldn’t require logging in.

**Comment by soodaayush** [comment]
@Carlgo11 This actually worked, thank you! It probably should be specified in contributing.md if possible.
