### ISSUE TITLE
Update Yahoo Mail

### ISSUE THREAD

**Issue by alexanderino** [jdavis/twofactorauth#7885]
### Site name

Yahoo Mail

### Site URL

https://mail.yahoo.com/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

[Yahoo! no longer requires a linked phone number to enable/activate 2FA](https://help.yahoo.com/kb/SLN5013.html#cont6). Please remove the warning tooltip (Exceptions and Restrictions) that states this.

Today, I successfully enabled 2FA on my Yahoo! account. My phone number has never been provided.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by orazioedoardo** [comment]
Do you need two email addresses linked though? Support page says two recovery methods.

**Comment by fletcherdodd** [comment]
You do need a recovery method to set up 2FA. This can be a phone number or email (as per below) so I'll adjust the note on there not remove it.
![image](https://github.com/2factorauth/twofactorauth/assets/7688583/99be37ad-a265-481d-8de2-dd29f6c9d8f6)

**Comment by alexanderino** [comment]
Many thanks for updating this, @fletcherdodd, and apologies for not showing my appreciation sooner.

**Comment by fletcherdodd** [comment]
No stress at all ☺️! Thanks for contributing.
