### ISSUE TITLE
Koho is not showing in the Canadian region

### ISSUE THREAD

**Issue by Niobium62** [jdavis/twofactorauth#7891]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:** Koho is not showing in the Canadian region. It only shows in Global

**Bug reproduction:** 
1. Click on the finance section
2. Scroll down to Kiva, where Koho should be under
3. Koho is not there

**Impacted devices:**

Both Chromium and Firefox browsers are affected

**Expected behavior:**

1. Click on the finance section
2. Scroll down to Kiva, where Koho should be under
3. Koho is there

**Additional information:**

Koho already has "ca" as a region in the json file, so it should already be working

**Comment by Carlgo11** [comment]
@Niobium62 you might need to clean your browser cache. KOHO is in the finance section in the Canadian page. I just looked it up myself.

**Comment by Niobium62** [comment]
Apologies, it worked for me
