### ISSUE TITLE
Update LINE

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#7904]
### Site name

LINE

### Site URL

https://line.me/

### Update reason

It now supports 2FA.

### Additional information

LINE enforces 2FA for all accounts using SMS.
This is requested when you install the LINE application on a new smartphone and attempt to log in to an existing account.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by fletcherdodd** [comment]
Hi @elvis-hrvat,
I have found [documentation](https://help.line.me/line/?contentId=20000438) on setting up 2FA for your LINE account, however it is not clear what methods are available. Could you please provide some screenshots of 2FA setup and/or login process?

> [!NOTE] 
> Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment like this: ![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

**Comment by fletcherdodd** [comment]
Closed as the user no longer exists and there is no link to any documentation or screenshots of 2FA methods.
