### ISSUE TITLE
Add Animate Online Shop

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#7912]
### Site name

Animate Online Shop

### Site URL

https://www.animate-onlineshop.jp/

### Documentation URL

https://www.animate-onlineshop.jp/faq/detail.php?id=1314

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Regions served

JP

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [x] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
What's described sounds more like authorization for specific user actions than authentication at the login phase.
We distinguish between the two in the section about authorization in [Contributing.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization).
Please confirm if this is the case or if 2FA is also prompted on login.

![Screenshot](https://github.com/2factorauth/twofactorauth/assets/3535780/d85e875b-8e21-40ea-91f0-d4d2a69c87cb)

**Comment by ghost** [comment]
In fact, it is also required at login.

**Comment by ghost** [comment]
I just tried it and it seems that SMS authentication is only required at login if the website administrator thinks it is suspicious.

**Comment by fletcherdodd** [comment]
Closed as the user no longer exists and this site doesn't meet the criteria according to the comments above.
