### ISSUE TITLE
Update Vanguard

### ISSUE THREAD

**Issue by kilimar** [jdavis/twofactorauth#7916]
### Site name

Vanguard

### Site URL

https://investor.vanguard.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

The site now offers authentication using FIDO2 hardware.  Information can be found under "Security keys" at
https://investor.vanguard.com/trust-security/security-center#modal-keys

I *believe* you can disable SMS as backup.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
We already list Vanguard as supporting FIDO2.
https://github.com/2factorauth/twofactorauth/blob/37b6f191aa15f062fe56bdc5801e3ac671a6bc84/entries/v/vanguard.com.json#L9
