### ISSUE TITLE
2ファクター

### ISSUE THREAD

**Issue by Takuya4949** [jdavis/twofactorauth#7946]
- [ ] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

**Bug reproduction:**

**Impacted devices:**

**Expected behavior:**

**Additional information:**

**Comment by Carlgo11** [comment]
Hi @Takuya4949,
I'm not sure what you're trying to do here, but as you haven't provided any information except 2ファクタ, I'm going to close this issue.
Have a nice day!
