### ISSUE TITLE
Update eBay

### ISSUE THREAD

**Issue by Oxidela** [jdavis/twofactorauth#7959]
### Site name

eBay

### Site URL

https://www.ebay.com/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Sign-in > Account Settings > Sign-In and security

Supports:
- Basic sign-in with password
- 2FA: Authenticator app, App notification, SMS (To setup these, a email or SMS verification is required)
- eBay App: Use the eBay app tp sign-in
- Social: Use your social accounts to sign-in and checkout
- Hardware Key: use your FIDO 2-complient security key (confirming that it did not accept my Yubikey 4, seems only 5 works)

![2FA_eBay_2FA](https://github.com/2factorauth/twofactorauth/assets/93446756/b5790f1b-bd1b-4c81-b46a-8d8b53911ee0)
![2FA_eBay_Settings](https://github.com/2factorauth/twofactorauth/assets/93446756/886fc197-f2b0-4c4b-9e8c-e61165f68bd6)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

Edit:
Accidently closed issue. Additional restrictions on hardware keys: https://community.ebay.com/t5/Ask-a-Mentor/Support-for-registering-multiple-security-keys/td-p/32804043

**Comment by Oxidela** [comment]
Additional restrictions with hardware keys: https://community.ebay.com/t5/Ask-a-Mentor/Support-for-registering-multiple-security-keys/td-p/32804043

**Comment by Carlgo11** [comment]
Hello @Oxidela,
Thanks for your submission!
We already list eBay supporting TOTP, SMS and push notifications through the eBay app.
As the FIDO2-security key option bypasses the need for a password, we don’t list that as 2FA.
[Passkeys Directory](https://passkeys.2FA.directory) does however list eBay as supporting password less authentication.
