### ISSUE TITLE
Add Rumble

### ISSUE THREAD

**Issue by WesVanVugt** [jdavis/twofactorauth#7982]
### Site name

Rumble

### Site URL

https://rumble.com

### Facebook

https://facebook.com/rumblevideo

### Twitter

@rumblevideo

### Email address

support@rumble.com

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Rumble will not be added to 2FA Directory. Please see our position in [PR #7676](https://github.com/2factorauth/twofactorauth/pull/7676#issuecomment-1629712875).
