### ISSUE TITLE
Add HSBC Australia

### ISSUE THREAD

**Issue by jimmyvanau** [jdavis/twofactorauth#7990]
### Site name

HSBC Australia

### Site URL

https://www.hsbc.com.au

### Documentation URL

https://www.hsbc.com.au/ways-to-bank/support/digital-secure-key/

### Recovery Documentation URL

https://www.hsbc.com.au/ways-to-bank/support/digital-secure-key/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Regions served

Australia

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
@jimmyvanau if you intend on making a pull request yourself, there's no need to also create an issue for it :wink:

**Comment by jimmyvanau** [comment]
thanks @Carlgo11 ! Have submitted #7989

**Comment by jimmyvanau** [comment]
Not sure what is wrong with https://github.com/2factorauth/twofactorauth/actions/runs/8698198887/job/23855386205
URL seems valid

**Comment by Carlgo11** [comment]
That's just a little script to ease the work for us maintainers. It failing does not affect your issue/pr; it just makes my workload a bit more :sweat_smile: 

Closing this issue now as #7989 is merged.
