### ISSUE TITLE
Update Microsoft Azure

### ISSUE THREAD

**Issue by influential-eliot** [jdavis/twofactorauth#7994]
### Site name

Microsoft Azure

### Site URL

https://portal.azure.com

### Update reason

Other (please describe below).

### Additional information

This is not just for the Azure site, but for any site that supports Entra ID based logins with MFA.

The charts that I could see didn't indicate that TOTP was an option. However it very much is, and using TOTP is my only method of MFA for Microsoft sites.

I checked a few other tickets about this ... and (as I recall from another ticket) 'Hardware' (_used to be 'Hardware token' ?_) generically means TOTP. However it is not checked on any of the MS sites that came up on a microsoft search (including Azure) on the directory.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
@influential-eliot Microsoft Azure and all the other Microsoft services listed on 2FA Directory, already list TOTP as being supported.

See [entries/a/azure.microsoft.com.json](https://github.com/2factorauth/twofactorauth/blob/1612133c6082b754fb4565b0faa16a3663d9202b/entries/a/azure.microsoft.com.json#L7)

![screenshot](https://github.com/2factorauth/twofactorauth/assets/3535780/e511377f-76d0-4915-b2ec-842fc229c34b)

**Comment by hkamran80** [comment]
For the record, "Hardware" refers to FIDO2/U2F and other hardware-based devices. TOTP falls under "Software".

**Comment by influential-eliot** [comment]
You're absolutely right, @hkamran80 and @Carlgo11 ... I had misremembered this quote, here. For some reason I'd thought it had said hardware.

I'm an idiot! 😅 Sorry, folks!

**Comment by influential-eliot** [comment]
Closing!
