### ISSUE TITLE
Update QNAP

### ISSUE THREAD

**Issue by alramon** [jdavis/twofactorauth#8069]
### Site name

QNAP

### Site URL

https://account.qnap.com

### Update reason

Other (please describe below).

### Additional information

QNAP have their support forums under forum.qnap.com, and the site does not support 2FA. Only account.qnap.com does.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by Carlgo11** [comment]
Hello @alramon,
Thanks for creating an issue!

Could you describe what you'd want to have changed? The QNAP entry on the 2FA Directory links to their main page ([www.qnap.com](https://www.qnap.com)), which is what we always do when listing a service. We don't list the QNAP forum, and will not, as forums are [excluded](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#forums) from the 2FA Directory.

**Comment by alramon** [comment]
Hi @Carlgo11 ,
Thank you for your response.

I did not read about the forums exclusion category. The entry is then perfectly set and I close this issue. I will also propose a change to Bitwarden to honor this exclusion so QNAP forums do not popup in their MFA capable sites report results which use 2FA Directory as source.
