### ISSUE TITLE
Update Withings

### ISSUE THREAD

**Issue by d4k0** [jdavis/twofactorauth#8100]
### Site name

Withings

### Site URL

https://withings.com

### Update reason

It now supports 2FA., The methods of 2FA that it supports have changed.

### Additional information

Withings apparently also added support for TOTP a few months ago, today I happened to see it in my account and activated it.

Here is a support article about it:

https://support.withings.com/hc/en-us/articles/21366971036689-Withings-App-Web-Dashboard-Frequently-Asked-Questions-about-MFA

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by fletcherdodd** [comment]
Hi @d4k0,

Thanks for creating the issue. I have updated what 2FA options the support and the documentation.
