### ISSUE TITLE
Add HBO Max

### ISSUE THREAD

**Issue by Nathanymous** [jdavis/twofactorauth#8121]
### Site name

HBO Max

### Site URL

https://www.max.com/

### Facebook

https://www.facebook.com/HBOMax

### Twitter

https://x.com/hbomax

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Hi @Nathanymous, we already have Max in the directory. If you searched for "HBO Max", you wouldn't have found it because it was changed to "Max" when they rebranded it.
