### ISSUE TITLE
2fa.directory site constantly reloads / refreshes; is unviewable

### ISSUE THREAD

**Issue by ElectricFeet** [jdavis/twofactorauth#8130]
https://2fa.directory seems to be constantly reloading itself. It redirects me to https://2fa.directory/int/ and thereafter just keeps looping trying to reload. The site is unviewable.

MacOS Sonoma 14.5; Firefox 127.02 / Safari 17.5 (with and without extensions): neither works.
iPadOS 17.5.1 Firefox Focus / Safari (with and without extensions): neither works.

Wed 17 Jul 2024 20:15 UTC

**Comment by Carlgo11** [comment]
Thanks for the report @ElectricFeet!
I submitted a fix that should be deployed globally within a couple of minutes.

**Comment by ElectricFeet** [comment]
Thanks @Carlgo11 !
