### ISSUE TITLE
Add DownloadAuthenticator

### ISSUE THREAD

**Issue by DownloadAuthenticator** [jdavis/twofactorauth#8134]
### Site name

DownloadAuthenticator

### Site URL

https://downloadauthenticator.com/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [ ] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

**Comment by Carlgo11** [comment]
@DownloadAuthenticator, we do not list 2FA providers.
Furthermore, the [2FA Service](https://downloadauthenticator.com/authenticator-app-service/) list you provide on your website using data from the 2FA Directory, is in violation of our [license](https://github.com/2factorauth/twofactorauth/blob/master/LICENSE.md).

**Comment by DownloadAuthenticator** [comment]
Dear ,

Thank you for bringing this to our attention. We apologize for the oversight and any inconvenience it may have caused. We will promptly correct the 2FA Service list on our website within the next two days to comply with your licensing terms.

Best regards,
