### ISSUE TITLE
v3 API URL 'https://api.2fa.directory/v3/tfa.json' returns 404

### ISSUE THREAD

**Issue by joshuacant** [jdavis/twofactorauth#8139]
- [X] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**
The All 2FA-supporting sites 'https://api.2fa.directory/v3/tfa.json' v3 API url returns a github 404 error document instead of valid JSON

**Bug reproduction:**
Open https://api.2fa.directory/v3/tfa.json

**Impacted devices:**
All

**Expected behavior:**
https://api.2fa.directory/v3/tfa.json returns valid JSON

**Comment by Carlgo11** [comment]
Thanks for the bug report @joshuacant!
_tfa.json_ and _tfa.json.sig_ are now back.

Just out of curiosity, what's your use-case where you need to use _tfa.json_ instead of a narrower output, like _totp.json_ or _u2f.json_?

**Comment by joshuacant** [comment]
Thanks for fixing this so fast!

The question about use-case would have to be answered by @Rookiestyle who develops the KeePassOTP plugin (https://github.com/Rookiestyle/KeePassOTP) for an application called KeePass. I am just an end user of that plugin. It showed me an error message today when using it. I did a little digging and found this 404 was the root cause, so I raised the issue here.

**Comment by Carlgo11** [comment]
Oh, I didn't realize that you were an end-user 😅

@Rookiestyle I went through [your code](https://github.com/Rookiestyle/KeePassOTP/blob/e7cdd931966da84daa3f92672e09dff9b407c975/src/DAO/TFASites.cs) and I don't see any reason why it would need to fetch all 2FA-supporting sites instead of just those with TOTP support. Am I missing something?

**Comment by Rookiestyle** [comment]
@Carlgo11 [This code](https://github.com/Rookiestyle/KeePassOTP/blob/e7cdd931966da84daa3f92672e09dff9b407c975/src/KPOTP_Details.cs) is executed when a KeePass user opens the details of an entry. My plugin checks whether 2FA is possible and shows all the available options to the user.

Additionally, in the entry overview my plugin shows a column with the calculated OTP value or "Setup TFA" if this is possible - based on tfa.json.
Also it's possible for a user to define that he has "other 2FA" configured. *Other* being something different than  TOTP. This way they can make the "Setup TFA" string go away if they e. g. have SMS active as second factor
