### ISSUE TITLE
Add Nabtrade

### ISSUE THREAD

**Issue by stevene1919** [jdavis/twofactorauth#8159]
### Site name

Nabtrade

### Site URL

https://nabtrade.com.au

### Documentation URL

https://www.nabtrade.com.au/support/security

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Regions served

Australia

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

nabtrade is a large Australian financial company that lets you trade stocks

**Comment by fletcherdodd** [comment]
Hi @stevene1919,

The documentation you have linked doesn't seem to reference anything about the 2FA methods they support. Are you able to attach screenshots of the 2FA setup and/or login process.

> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment like this:
![image](https://github.com/user-attachments/assets/703fef5e-3d16-4716-9080-fd16ccdb8e12)

Also nabtrade appears to use the same authentication system as their main banking services. Can you confirm whether or not you use a different User ID/Password to login to your nabtrade account?

**Comment by stevene1919** [comment]
nabtrade definitely uses seperate authentication than nab, technically different companies (owned by nab). i have seperate account numbers for both. ubank also is technically a nab company and across all these services you can link accounts, but you do get seperate account numbers. the only similarity seems to be the branding.

it appears they don't have 2fa for signing in, only for transactions.

![Screenshot_20240830-231352_nabtrade](https://github.com/user-attachments/assets/c2810059-9e99-4db1-ad49-cf0dad7276b6)

**Comment by stevene1919** [comment]
closing as account id is same. may still want to list the site as you can have accounts with either and both.

2fa sms codes only for transactions

**Comment by hkamran80** [comment]
> 2fa sms codes only for transactions

This sounds like [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization).
