### ISSUE TITLE
Add Transperth

### ISSUE THREAD

**Issue by stevene1919** [jdavis/twofactorauth#8161]
### Site name

Transperth

### Site URL

https://www.transperth.wa.gov.au/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Regions served

Australia

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

transperth is a Western Australian government public transport agency. it has sms, email and in app tokens

**Comment by fletcherdodd** [comment]
Hi @stevene1919 

Are you able to find any links to documentation on the 2FA setup process on their website? I was unable to locate any.

If no documentation is available or you can't find it, please attach screenshots of the 2FA setup and/or login process.

> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment like this:
![IMG_5331](https://github.com/user-attachments/assets/2f2c979b-403e-4a71-bddb-2be6bec90282)

**Comment by stevene1919** [comment]
![Screenshot_20240830-230236](https://github.com/user-attachments/assets/f45863c6-e335-46bb-922d-0f6c11c6d3a8)
![Screenshot_20240830-230206](https://github.com/user-attachments/assets/9c44532e-46fa-497e-8149-837b03aa640c)
