### ISSUE TITLE
Update iiNet

### ISSUE THREAD

**Issue by stevene1919** [jdavis/twofactorauth#8163]
### Site name

iiNet

### Site URL

https://iinet.net.au

### Update reason

It now supports 2FA.

### Additional information

iiNet support sms authentication on their toolbox. they are a relatively large Australian ISP. 

iiNet is owned by TPG but have their own systems.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by fletcherdodd** [comment]
Hi @stevene1919,
Thanks for raising this issue. I have already completed a PR (#8109) for iiNet's support of 2FA a couple of months ago. Just make sure to double check the site listings and current PRs before submitting issues.
