### ISSUE TITLE
Update Coles

### ISSUE THREAD

**Issue by stevene1919** [jdavis/twofactorauth#8166]
### Site name

Coles

### Site URL

https://coles.com.au

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

coles only support sms 2fa

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by fletcherdodd** [comment]
Hi @stevene1919,
Do you have anything documenting that they have removed email 2FA? I still appear to have the option to be emailed a code instead of an SMS one.
![image](https://github.com/user-attachments/assets/80519917-00d9-43a9-976f-9a141f39f89e)

**Comment by stevene1919** [comment]
my mistake, appears the email I got being a coles plus subscriber saying i needed to enable sms authentication isn't necessary when your not. as I'm no longer a coles plus member i cant check, but i can see both now.
