### ISSUE TITLE
Add Appodeal

### ISSUE THREAD

**Issue by Rabadash8820** [jdavis/twofactorauth#8195]
### Site name

Appodeal

### Site URL

https://appodeal.com/

### Documentation URL

https://app.appodeal.com/v3/profile/edit

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

I couldn't find any specific documentation or recovery documentation, but the account settings page has a little "?" tooltip that basically serves as their documentation.

**Comment by hkamran80** [comment]
Please attach some screenshots of the 2FA setup process, login process, or management screen. Please blur or crop out any personal or sensitive information.

**Comment by Rabadash8820** [comment]
Does this work?

![image](https://github.com/user-attachments/assets/5d0ad183-e7fe-4a8f-893d-8af63fad2d5d)

**Comment by hkamran80** [comment]
That does not work. What is in the dropdown?

**Comment by Rabadash8820** [comment]
The 2FA options (disabled, email, or OTP). I would probably need multiple screenshots to capture the various UI states. Is that ok?

**Comment by hkamran80** [comment]
Just the 2FA options would be good.

**Comment by Rabadash8820** [comment]
Okay, how bout this?

![image](https://github.com/user-attachments/assets/c3592ea6-aacf-4f7d-9320-77e57508acb2)

**Comment by hkamran80** [comment]
That's good. Thank you.
