### ISSUE TITLE
Update PKO Bank Polski, added support for U2F

### ISSUE THREAD

**Issue by Encryptionus** [jdavis/twofactorauth#8209]
### Site name

PKO Bank Polski

### Site URL

https://pkobp.pl

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

PKO Bank Polski quietly started supporting U2F security keys as a second factor for signing into bank accounts (at least for individual customers), through its e-banking service ipko.pl
Here's the bank's page mentioning it (in Polish): https://www.pkobp.pl/klient-indywidualny/aplikacja-iko-ipko/bezpieczenstwo/logowanie-z-kluczem-bezpieczenstwa

As far as I know there is no requirement for coming to bank branch to activate the security key (unlike with ING Bank Śląski) but as of now, you can only register one security key to your bank account.

Update: Removed the second URL from "Site URL" because Github's CI was complaining.

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by kporembinski** [comment]
New JSON:

```{
  "PKO Bank Polski": {
    "domain": "pkobp.pl",
    "url": "https://www.pkobp.pl/",
    "tfa": [
      "sms",
      "u2f",
      "custom-software"
    ],
    "documentation": "https://iko.pkobp.pl/funkcje/mobilna-autoryzacja/",
    "custom-software": [
      "IKO App"
    ],
    "categories": [
      "banking"
    ],
    "regions": [
      "pl"
    ]
  }
}```

**Comment by hkamran80** [comment]
@kporembinski Do you want to open a PR for this?
