### ISSUE TITLE
Update Fidelity Investments

### ISSUE THREAD

**Issue by holow29** [jdavis/twofactorauth#8250]
### Site name

Fidelity Investments

### Site URL

https://www.fidelity.com/

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Now supports TOTP (https://www.fidelity.com/security/extra-security-login  : "Authenticator Apps")

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by hkamran80** [comment]
Hi @holow29, we already updated Fidelity in the directory with PR #8174.

**Comment by holow29** [comment]
Oops! My mistake - I misunderstand how to read the website. Thanks.

**Comment by hkamran80** [comment]
No worries! Thanks for contributing!
